### PR TITLE
Introduce checkpoint keylists & history, merge and transplant for DynamoDB

### PR DESCRIPTION
**Pull request by jacques-n**
* Add type attributes to all objects and validate on load
* Change representation of a L1 to include a parent list instead of a single parent
* Change representation of a commit to include list of keys added and/or removed
* Store full and incremental keylists to improve key retrieval efficiency
* Use parent lists to improve commit history retrieval efficiency
* Add support for Merge operation
* Add support for Transplant operation

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/303)

### CODE REVIEW

**Review by rymurr — CHANGES_REQUESTED** [review]
> Reviewed 7 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/303)* status: 6 of 19 files reviewed, 1 unresolved discussion (waiting on @jacques-n, @laurentgo, and @rymurr)

___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/KeyMutation.java, line 28 at r2](https://reviewable.io/reviews/projectnessie/nessie/303#-MK-gfvhEBqzXzI7HA93:-MK-gfvhEBqzXzI7HA94:b-u6jept) ([raw file](https://github.com/projectnessie/nessie/blob/00f58296f36f1c78e0a771900cce8cc51f103bb4/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/KeyMutation.java#L28)):*
> ```Java
> abstract class KeyMutation {
> 
>   static final String DELETE = "d";
> ```

this is weird to my eye. Are both needed?

**Comment by rymurr** [comment]
just a few cosmetic issues. Otherwise lgtm. A very dense PR!

**Review by laurentgo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/303)* status: 6 of 19 files reviewed, 3 unresolved discussions (waiting on @jacques-n, @laurentgo, and @rymurr)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/303#-MK0TCkUBp6tHp4UqMpv:-MK0TCkV80A1rk-eBaxB:b-gusktr) (no related file):*
I guess it's a bit short on testing? I only saw one small integration test, am I correct?

---
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/LoadStep.java, line 38 at r2](https://reviewable.io/reviews/projectnessie/nessie/303#-MK0Srr1E4Zhn6IhTALF:-MK0Srr2-WiRpSkcE7PK:bs8iemg) ([raw file](https://github.com/projectnessie/nessie/blob/00f58296f36f1c78e0a771900cce8cc51f103bb4/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/LoadStep.java#L38)):*
> ```Java
> 
>   public LoadStep(Collection<LoadOp<?>> ops) {
>     this(ops, () -> Optional.empty());
> ```

(style) Optional::empty
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/ParentList.java, line 34 at r2](https://reviewable.io/reviews/projectnessie/nessie/303#-MK0SxwDEOVziM-DNF2u:-MK0SxwDEOVziM-DNF2v:b-p39l67) ([raw file](https://github.com/projectnessie/nessie/blob/00f58296f36f1c78e0a771900cce8cc51f103bb4/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/ParentList.java#L34)):*
> ```Java
> abstract class ParentList {
> 
>   static final int MAX_PARENT_LIST_SIZE = 50;
> ```

should it be tunable (system property?)

**Review by jacques-n — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/303)* status: 6 of 19 files reviewed, 3 unresolved discussions (waiting on @laurentgo and @rymurr)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/303#-MK0TCkUBp6tHp4UqMpv:-MK0xdH01Tko6AXPiy0H:b514017) (no related file):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I guess it's a bit short on testing? I only saw one small integration test, am I correct?
</blockquote></details>

No new functionality introduced. Additional covers edge cases the base tests didn't cover.

---
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/KeyMutation.java, line 28 at r2](https://reviewable.io/reviews/projectnessie/nessie/303#-MK-gfvhEBqzXzI7HA93:-MK0xpTM5NuQ2EXxaXeW:b-hfpv0l) ([raw file](https://github.com/projectnessie/nessie/blob/00f58296f36f1c78e0a771900cce8cc51f103bb4/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/KeyMutation.java#L28)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

this is weird to my eye. Are both needed?
</blockquote></details>

removed
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/LoadStep.java, line 38 at r2](https://reviewable.io/reviews/projectnessie/nessie/303#-MK0Srr1E4Zhn6IhTALF:-MK0xvCg02uyRJh7WvcA:b-yrxps1) ([raw file](https://github.com/projectnessie/nessie/blob/00f58296f36f1c78e0a771900cce8cc51f103bb4/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/LoadStep.java#L38)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

(style) Optional::empty
</blockquote></details>

ack, will use in future.
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/ParentList.java, line 34 at r2](https://reviewable.io/reviews/projectnessie/nessie/303#-MK0SxwDEOVziM-DNF2u:-MK0xwWC7BYlAP8BR-yL:bse3y15) ([raw file](https://github.com/projectnessie/nessie/blob/00f58296f36f1c78e0a771900cce8cc51f103bb4/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/impl/ParentList.java#L34)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

should it be tunable (system property?)
</blockquote></details>

I'm evaluating moving that. Not sure it should be configurable across time.

**Review by rymurr — DISMISSED** [review]
I am ok with this, its a bit dense in some of the dynamo parts but the same pattern as the jgit impl is clear to me. +1 from me

> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/303#-:-MK5XoWvEmQUiJiOm-G1:b-fivrtv)* status: 5 of 23 files reviewed, 3 unresolved discussions (waiting on @laurentgo and @rymurr)

**Pull request merged**
