### PR TITLE
Turn off the unicode check in ErrorProne

### PR DESCRIPTION
**Pull request by ajantha-bhat**
Turn off the unicode check in ErrorProne as it throws invalid error in IDE.

image

### CODE REVIEW

**Comment by XN137** [comment]
as an alternative we could try adding `-Xep:UnicodeInCode:OFF` here instead:
https://github.com/projectnessie/nessie/blob/eaca0145b4c4c76bda3dbbbbd30a07752f4d6552/pom.xml#L1281
(and dont lose anything because that check was only added in `2.11.0`)

wdyt?

**Comment by ajantha-bhat** [comment]
> as an alternative we could try adding -Xep:UnicodeInCode:OFF here instead:

@XN137 : It will mask the actual errors also ?

**Comment by XN137** [comment]
it will disable the check yes, but as i said, going back to the old version does not have this check at all.

**Comment by snazy** [comment]
Don't see this error with IDEA Build #IU-213.7172.25, built on March 15, 2022

**Comment by ajantha-bhat** [comment]
> Don't see this error with IDEA Build #IU-213.7172.25, built on March 15, 2022

@snazy : we merged this (https://github.com/projectnessie/nessie/pull/3640) two days ago

**Comment by ajantha-bhat** [comment]
> it will disable the check yes, but as i said, going back to the old version does not have this check at all.

ok for me, Let's see what others think.

**Comment by snazy** [comment]
> > Don't see this error with IDEA Build #IU-213.7172.25, built on March 15, 2022
> 
> @snazy : we merged this (#3640) two days ago

Yes??? Can you maybe check the build number of IDEA that you're using??

**Comment by ajantha-bhat** [comment]
> Yes??? Can you maybe check the build number of IDEA that you're using??

where can I find it? I googled it, it pointed me to intellij version instead of build version.
Also build itself is failing for me, so there won't be a build number ?

image

**Comment by XN137** [comment]
it still happens for me, even with the march 15 intellij build:
image

**Comment by ajantha-bhat** [comment]
build number
image

**Review by XN137 — DISMISSED** [review]
maybe add a comment why we disable it (so future us can now when we could try to re-enable it again)

but +1 as is

**Comment by ajantha-bhat** [comment]
Even if it is solved by upgrading IDE, we can't force everyone to use the latest IDE. So, tuning it off as @XN137 suggested.
Reverting also not a good idea as someone might merge it again from dependabot.

**Comment by ajantha-bhat** [comment]
> maybe add a comment why we disable it (so future us can now when we could try to re-enable it again)
Added the comment.

**Review by nastra — APPROVED** [review]

**Pull request merged**
