### PR TITLE
Refactor error reporting in Nessie API

### LINKED ISSUE #3225: 404 (Not Found) server responses on invalid base URL lead to UndeclaredThrowableException in the java client, which is confusing
test code (note the deliberate mistake of using `/v2` in the URI):
```
NessieApiV1 api =
      HttpClientBuilder.builder()
        .withUri(new URI("http://127.0.0.1:19120/api/v2"))
        .build(NessieApiV1.class);
    api.getConfig();
```
Exception:
```
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy12.getConfig(Unknown Source)
	at org.projectnessie.client.http.v1api.HttpApiV1.getConfig(HttpApiV1.java:54)
	at org.projectnessie.client.TestNessieHttpClient.test(TestNessieHttpClient.java:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.projectnessie.error.NessieNotFoundException: Not Found
	at org.projectnessie.client.rest.ResponseCheckFilter.checkResponse(ResponseCheckFilter.java:74)
	at org.projectnessie.client.rest.NessieHttpResponseFilter.filter(NessieHttpResponseFilter.java:35)
	at org.projectnessie.client.http.HttpRequest.lambda$executeRequest$3(HttpRequest.java:150)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.projectnessie.client.http.HttpRequest.executeRequest(HttpRequest.java:150)
	at org.projectnessie.client.http.HttpRequest.get(HttpRequest.java:181)
	at org.projectnessie.client.http.HttpConfigClient.getConfig(HttpConfigClient.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.projectnessie.client.http.NessieHttpClient$ExceptionRewriter.invoke(NessieHttpClient.java:160)
	... 70 more
```

Throwing a `NessieNotFoundException` directly would be more user-friendly, I guess.

### PR DESCRIPTION
**Pull request by dimas-b**
* Avoid throwing UndeclaredThrowableException in java client

* Unwrap HttpClientException only if the root cause exception is
  a BaseNessieClientServerException. Those exception classes are
  expected to be properly declared on the corresponding API methods.

* Add NessieRuntimeException (and sub-classes) to represent unchecked
  exceptions that originate from Nessie service code.

* Add javadoc to exception classes to clarify the responsibility scope
  of errors reported by means of those exceptions (Nessie vs. non-Nessie)

* Add enums for Nessie-controlled BAD_REQUEST, FORBIDDEN and TOO_MANY_REQUESTS
  errors to ErrorCode.
  
* Move HTTP status codes for Nessie-controlled error responses to ErrorCode.
  
* Report NessieServiceException (and sub-classes) only if the error response
  does not include a NessieError object (and a Nessie ErrorCode).
  
* Use NessieServiceException only to report container-level HTTP error responses
  (e.g. mistakes in base Nessie URI). 

Fixes #3225

### CODE REVIEW

**Comment by snazy** [comment]
Some do declare `NessieNotFoundException' . But the issue here is that  HTTP/404 can have different causes. First, an HTTP/404 returned by Nessie itself and an HTTP/404 returned by something in the middle meaning the configured base URL is wrong. Maybe the HttpClient needs a change to throw `NessieNotFoundException` only if the response body represents a valid Nessie error response and if not throw a meaningful runtime exception.

Throwing `NessieNotFoundException` from methods that declare it but the base URL is wrong is probably also confusing.

Probably also need some checks for HTTP/400 + 502 and such and throw a meaningful runtime exception, if the response body doesn't represent a valid Nessie exception.

**Comment by dimas-b** [comment]
I reworked this PR a bit. Please have a look.

@snazy : I'm not sure what you mean to do with 502 errors. Currently, they would be represented by a `NessieServiceException`... Do you think we ought to have a more specific exception type for them?

**Comment by snazy** [comment]
What I mean is to not wrap responses as `Nessie*Exception`, if Nessie didn't cause them.

Examples:

A legit Nessie excepiton:
```
$ curl -v http://localhost:19120/api/v1/trees/tree/foo
*   Trying 127.0.0.1:19120...
* Connected to localhost (127.0.0.1) port 19120 (#0)
> GET /api/v1/trees/tree/foo HTTP/1.1
> Host: localhost:19120
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< content-length: 163
< 
{
  "status" : 404,
  "reason" : "Not Found",
  "message" : "Named reference 'foo' not found",
  "errorCode" : "REFERENCE_NOT_FOUND",
  "serverStackTrace" : null
* Connection #0 to host localhost left intact
}
```

A HTTP/404 not from Nessie:
```
$ curl -v http://localhost:19120/blaaaaaaaaaaaah/trees/tree/foo
*   Trying 127.0.0.1:19120...
* Connected to localhost (127.0.0.1) port 19120 (#0)
> GET /blaaaaaaaaaaaah/trees/tree/foo HTTP/1.1
> Host: localhost:19120
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-type: text/html; charset=utf-8
< content-length: 53
< 
* Connection #0 to host localhost left intact
<html><body><h1>Resource not found</h1></body></html>
```

I think, we shouldn't wrap the latter as a `NessieNotFoundException` - and similar for all other HTTP status codes.
I.e. those that are not `application/json` and/or response bodies that cannot be parsed into a `org.projectnessie.error.NessieError`. WDYT?

**Comment by dimas-b** [comment]
SGTM ^ This PR already uses a different exception (not `NessieNotFoundException`) for non-Nessie errors, but I'll refine this PR further.

**Review by snazy — APPROVED** [review]

**Comment by snazy** [comment]
LGTM!

**Pull request merged**
