### PR TITLE
Use Iceberg's CatalogUtil function in demo

### PR DESCRIPTION
**Pull request by rymurr**
simplify the creation of a `NessieCatalog` in the demo by using icebergs `CatalogUtil` methods. 

**NOTE** the `uri` has been changed back to `url` until iceberg `v0.12.0` is released. The `uri` change currently hasn't been released on the iceberg side.

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/973)

### CODE REVIEW

**Comment by rymurr** [comment]
tbf the demo should prob get (mostly) translated to SQL. This is a bigger patch and I am inclined to wait for the apache/iceberg#2269 changes to be released

**Review by snazy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @rymurr)

___
*[python/demo/nessie-iceberg-demo.ipynb, line 32 at r1](https://reviewable.io/reviews/projectnessie/nessie/973#-MW8vM523GZaoEss1XU6:-MW8vM533iQej8fWQUoD:b-5vcz3l) ([raw file](https://github.com/projectnessie/nessie/blob/6909e3ae457da697870db143b7c75d92331cf165/python/demo/nessie-iceberg-demo.ipynb#L32)):*
> ```
>     "conf.set(\"spark.sql.execution.pyarrow.enabled\", \"true\")\n",
>     "conf.set(\"spark.sql.catalog.nessie.warehouse\", 'file://' + os.getcwd() + '/spark_warehouse')\n",
>     "conf.set(\"spark.sql.catalog.nessie.url\", \"http://localhost:19120/api/v1\")\n",
> ```

That's confusing. `NessieClient.Builder.fromBuilder()` uses `NessieConfigConstants.CONF_NESSIE_URI` (i.e. `uri` for this parameter).
___
*[python/demo/nessie-iceberg-demo.ipynb, line 130 at r1](https://reviewable.io/reviews/projectnessie/nessie/973#-MW8vfFN7EmamrwEMm5A:-MW8vfFN7EmamrwEMm5B:b7f1yhf) ([raw file](https://github.com/projectnessie/nessie/blob/6909e3ae457da697870db143b7c75d92331cf165/python/demo/nessie-iceberg-demo.ipynb#L130)):*
> ```
>    "outputs": [],
>    "source": [
>     "catalog = jvm.CatalogUtil.loadCatalog(\"org.apache.iceberg.nessie.NessieCatalog\", \"nessie\", {'ref': 'dev', 'url': 'http://localhost:19120/api/v1', \"warehouse\": 'file://' + os.getcwd() + '/spark_warehouse'}, sc._jsc.hadoopConfiguration())\n",
> ```

The CatalogUtil change looks good to me.
Not sure about the `uri` -> `url` change.

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @rymurr and @snazy)

___
*[python/demo/nessie-iceberg-demo.ipynb, line 32 at r1](https://reviewable.io/reviews/projectnessie/nessie/973#-MW8vM523GZaoEss1XU6:-MW8waGkCxf0HxU9g-Ch:bxpr70n) ([raw file](https://github.com/projectnessie/nessie/blob/6909e3ae457da697870db143b7c75d92331cf165/python/demo/nessie-iceberg-demo.ipynb#L32)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

That's confusing. `NessieClient.Builder.fromBuilder()` uses `NessieConfigConstants.CONF_NESSIE_URI` (i.e. `uri` for this parameter).
</blockquote></details>

Agreed. But this is for `iceberg-spark3-runtime-apache-iceberg-0.11.0.jar` which still has `0.3.0` of the `NessieClient`

**Review by snazy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @rymurr)

___
*[python/demo/nessie-iceberg-demo.ipynb, line 32 at r1](https://reviewable.io/reviews/projectnessie/nessie/973#-MW8vM523GZaoEss1XU6:-MW8x4I_984P0HS10t2W:b-p4xzab) ([raw file](https://github.com/projectnessie/nessie/blob/6909e3ae457da697870db143b7c75d92331cf165/python/demo/nessie-iceberg-demo.ipynb#L32)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Agreed. But this is for `iceberg-spark3-runtime-apache-iceberg-0.11.0.jar` which still has `0.3.0` of the `NessieClient`
</blockquote></details>

Hum, right. Mind opening a "blocker" issue for later?

**Pull request merged**
