### PR TITLE
Switch to OpenTelemetry in Nessie Quarkus server

### PR DESCRIPTION
**Pull request by snazy**

### CODE REVIEW

**Review by dimas-b — COMMENTED** [review]
Changes LGTM.

I tried the naive approach of running:
```
env QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT=http://localhost:55680 \
  java -jar servers/quarkus-server/build/quarkus-app/quarkus-run.jar 
```

... but did not get any traces reported for commits :thinking: 

Could you add a readme entry for setting up OTel, please?

**Comment by snazy** [comment]
Weird, I tried it with `-Dquarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://localhost:4317` before and it collected traces. Let me re-check.

**Comment by dimas-b** [comment]
I ran OTel servers in docker-composse following some (old) example

**Comment by snazy** [comment]
Works on my machine :tm: 
image

Buuut - maybe remove `env ` from your command line?

**Comment by snazy** [comment]
> I ran OTel servers in docker-composse following some (old) example

https://quarkus.io/guides/opentelemetry#run-the-application

**Comment by dimas-b** [comment]
Ah, I configured otlp/2 port

**Comment by dimas-b** [comment]
Yes, it works with port `4317`... I wonder why it did not work with `otlp/2`, though :thinking:

**Review by dimas-b — APPROVED** [review]

**Pull request merged**
