### PR TITLE
Gradle plugin for quarkus

### PR DESCRIPTION
**Pull request by rymurr**
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/301)

### CODE REVIEW

**Review by laurentgo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/301)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @rymurr)

___
*[.gitignore, line 54 at r2](https://reviewable.io/reviews/projectnessie/nessie/301#-MJX_7smDrorfEgYFM5z:-MJX_7smDrorfEgYFM6-:b8msb34) ([raw file](https://github.com/projectnessie/nessie/blob/4c3c0327760ca6e6cf47d5d51a686f53dbb3940a/.gitignore#L54)):*
> ```ignore
> # gradle
> 
> tools/apprunner-gradle-plugin/.gradle
> ```

is it better to only have one .gitignore or to create a new one under tools/apprunner-gradle-plugin?
___
*[.github/workflows/main.yml, line 76 at r2](https://reviewable.io/reviews/projectnessie/nessie/301#-MJX_TlP08oNkNsDzPCF:-MJX_TlP08oNkNsDzPCG:bty1t8z) ([raw file](https://github.com/projectnessie/nessie/blob/4c3c0327760ca6e6cf47d5d51a686f53dbb3940a/.github/workflows/main.yml#L76)):*
> ```YAML
>           restore-keys: ${{ runner.os }}-gradle
>       - name: Populate version from maven
>         run: mvn -B prepare-package --file ../pom.xml -pl :nessie-tools
> ```

shouldn't the maven artifact used instead?
___
*[tools/pom.xml, line 48 at r2](https://reviewable.io/reviews/projectnessie/nessie/301#-MJXa-D65bie-AGLOpKQ:-MJXa-D65bie-AGLOpKR:bz5ftgt) ([raw file](https://github.com/projectnessie/nessie/blob/4c3c0327760ca6e6cf47d5d51a686f53dbb3940a/tools/pom.xml#L48)):*
> ```XML
>               <path>apprunner-gradle-plugin/version.txt</path>
>               <lines>
>                 <line>${project.version}</line>
> ```

is the goal simply to get the version in a file? I think you can simply do it with a maven command, without having to add a plugin:
```
./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout
```
___
*[tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/QuarkusApp.java, line 223 at r2](https://reviewable.io/reviews/projectnessie/nessie/301#-MJXaxff5ocnAyZsT8Nt:-MJXaxff5ocnAyZsT8Nu:b-b5rl9w) ([raw file](https://github.com/projectnessie/nessie/blob/4c3c0327760ca6e6cf47d5d51a686f53dbb3940a/tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/QuarkusApp.java#L223)):*
> ```Java
>     }
>     rtProps = new Properties();
>     try (BufferedReader reader = Files.newBufferedReader(path)) {
> ```

let's make sure to use the UTF8 encoding

**Review by laurentgo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/301)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[.github/workflows/main.yml, line 76 at r2](https://reviewable.io/reviews/projectnessie/nessie/301#-MJX_TlP08oNkNsDzPCF:-MJnQI8c6Dlreav88hwz:b-g79uyd) ([raw file](https://github.com/projectnessie/nessie/blob/4c3c0327760ca6e6cf47d5d51a686f53dbb3940a/.github/workflows/main.yml#L76)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

since this is a different job the mvn artifact may not be available. I can instead run a cli script to pull the version out of the parent pom if you would rather do that?
</blockquote></details>

I didn't realized at first this was done to get the project version
___
*[tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/QuarkusApp.java, line 78 at r3](https://reviewable.io/reviews/projectnessie/nessie/301#-MJnQciwEDFcm4SGwH8O:-MJnQciwEDFcm4SGwH8P:brskjrr) ([raw file](https://github.com/projectnessie/nessie/blob/2a9811ac72a7428cb086143d44eb621ee26c5a83/tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/QuarkusApp.java#L78)):*
> ```Java
>   }
> 
>   public static QuarkusApp newApplication(Configuration configuration, Project project) {
> ```

I updated my config patch to split the newApplication in two parts, one maven specific and one for quarkus. Would that be helpful for the gradle plugin?
___
*[tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/StartTask.java, line 47 at r3](https://reviewable.io/reviews/projectnessie/nessie/301#-MJnRIk80nKQHdFXYHPm:-MJnRIk80nKQHdFXYHPn:brsaqh6) ([raw file](https://github.com/projectnessie/nessie/blob/2a9811ac72a7428cb086143d44eb621ee26c5a83/tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/StartTask.java#L47)):*
> ```Java
>       if (existingApplication()) {
>         getLogger().info("Quarkus application already started, incrementing counter.");
>         incrementCount();
> ```

tbh, I'm not sure I understand why this is necessary. Can gradle invoke multiple times the start task for the same execution?
___
*[tools/apprunner-maven-plugin/pom.xml, line 61 at r3](https://reviewable.io/reviews/projectnessie/nessie/301#-MJnRfMeBsBenRJVzh2J:-MJnRfMeBsBenRJVzh2K:b-4dt78k) ([raw file](https://github.com/projectnessie/nessie/blob/2a9811ac72a7428cb086143d44eb621ee26c5a83/tools/apprunner-maven-plugin/pom.xml#L61)):*
> ```XML
>     <plugins>
>       <plugin>
>         <groupId>ru.yaal.maven</groupId>
> ```

to be removed I guess?

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/301)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @laurentgo)

___
*[tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/QuarkusApp.java, line 78 at r3](https://reviewable.io/reviews/projectnessie/nessie/301#-MJnQciwEDFcm4SGwH8O:-MK-LutH-Hs34Wnh2sYp:blaeyup) ([raw file](https://github.com/projectnessie/nessie/blob/2a9811ac72a7428cb086143d44eb621ee26c5a83/tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/QuarkusApp.java#L78)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I updated my config patch to split the newApplication in two parts, one maven specific and one for quarkus. Would that be helpful for the gradle plugin?
</blockquote></details>

cool, will pick up once its merged
___
*[tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/StartTask.java, line 47 at r3](https://reviewable.io/reviews/projectnessie/nessie/301#-MJnRIk80nKQHdFXYHPm:-MK-KY_j-PREOKbfFm9R:b-keulqh) ([raw file](https://github.com/projectnessie/nessie/blob/2a9811ac72a7428cb086143d44eb621ee26c5a83/tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/StartTask.java#L47)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

tbh, I'm not sure I understand why this is necessary. Can gradle invoke multiple times the start task for the same execution?
</blockquote></details>

Yes. If we have 3 modules that need quarkus for tests then Gradle will run 3 quarkus tasks simultaneously at the start of the job. This allows one to win and the other to increment the usage count at the cost of blocking gradle until quarkus starts up and a static ref count. An easier approach would be to start quarkus once if needed and stop once if needed across the entire project. I haven't figured out how to express this in gradle tasks yet though.
___
*[tools/apprunner-maven-plugin/pom.xml, line 61 at r3](https://reviewable.io/reviews/projectnessie/nessie/301#-MJnRfMeBsBenRJVzh2J:-MK-LQg61Z3ii6QupaMS:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/2a9811ac72a7428cb086143d44eb621ee26c5a83/tools/apprunner-maven-plugin/pom.xml#L61)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

to be removed I guess?
</blockquote></details>

Done.

**Review by laurentgo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/301)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/StartTask.java, line 47 at r3](https://reviewable.io/reviews/projectnessie/nessie/301#-MJnRIk80nKQHdFXYHPm:-MK0PLap2vOVajHw9MoR:b-k7enyh) ([raw file](https://github.com/projectnessie/nessie/blob/2a9811ac72a7428cb086143d44eb621ee26c5a83/tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/StartTask.java#L47)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Yes. If we have 3 modules that need quarkus for tests then Gradle will run 3 quarkus tasks simultaneously at the start of the job. This allows one to win and the other to increment the usage count at the cost of blocking gradle until quarkus starts up and a static ref count. An easier approach would be to start quarkus once if needed and stop once if needed across the entire project. I haven't figured out how to express this in gradle tasks yet though.
</blockquote></details>

but I guess it's not the same execution but 3 different executions, isn't it? The compiler task would not only run once and block for the other modules until all modules are done?

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/301)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @laurentgo)

___
*[tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/StartTask.java, line 47 at r3](https://reviewable.io/reviews/projectnessie/nessie/301#-MJnRIk80nKQHdFXYHPm:-MK0QSCD9IfvC4nVoqRb:b-d2l7t0) ([raw file](https://github.com/projectnessie/nessie/blob/2a9811ac72a7428cb086143d44eb621ee26c5a83/tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/StartTask.java#L47)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

but I guess it's not the same execution but 3 different executions, isn't it? The compiler task would not only run once and block for the other modules until all modules are done?
</blockquote></details>

I am not 100% sure what you mean. Will try to answer: The 3 `quarkus-start` tasks will run simultaneously at the start of the gradle build. This would start 1 server and increment the ref count to 3. The first one would block the other two till its started. This blocks 2 threads in the gradle process but others are still making progress. Once all quarkus engines are 'started ' the build process continues as normal. The threaded, graph-based nature of gradle seems super powerful for certain tasks but it makes this type of task a bit annoying. Hope thats close to what you were asking?

**Comment by jacques-n** [comment]
Hey @rymurr and @laurentgo, let's get this wrapped up so we can start getting reviews on https://github.com/apache/iceberg/pull/1587

**Review by laurentgo — APPROVED** [review]
> Reviewed 3 of 15 files at r1, 1 of 6 files at r3, 3 of 4 files at r4, 1 of 10 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/301)* status: 8 of 18 files reviewed, 3 unresolved discussions (waiting on @laurentgo)

___
*[tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/QuarkusAppExtension.java, line 23 at r6](https://reviewable.io/reviews/projectnessie/nessie/301#-MKCKLU72gBhYLCFFSCQ:-MKCKLU72gBhYLCFFSCR:b-qsyuya) ([raw file](https://github.com/projectnessie/nessie/blob/a90c20c93f566bb8a8d105d5be5b4b4e0e4453ed/tools/apprunner-gradle-plugin/src/main/java/com/dremio/nessie/quarkus/gradle/QuarkusAppExtension.java#L23)):*
> ```Java
> 
> public class QuarkusAppExtension {
>   private MapProperty<String, Object> props;
> ```

final?

**Comment by rymurr** [comment]
fixed the 'final' but it dismissed the approval. Could I get another @laurentgo ? Or feel free to merge it :-)

**Review by laurentgo — COMMENTED** [review]
> Reviewed 1 of 15 files at r1, 8 of 10 files at r5, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/301)* status: all files reviewed, 3 unresolved discussions (waiting on @laurentgo)

**Review by laurentgo — APPROVED** [review]

**Pull request merged**
