### PR TITLE
reduce default L1 size

### PR DESCRIPTION
**Pull request by rymurr**
This PR reduces default L1 size from approx 4k to approx 1k. This is to fit inside the potentially limiting 1000 WCUs per partition.

See the discussion on #602

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/607)

### CODE REVIEW

**Comment by jacques-n** [comment]
Two quick thoughts: did you focus on InternalBranch size or L1 size? Our goal is for InternalBranch to hit 1k.

Also, it looks like you changed the l1 fanout size to 36. I was preferring a prime for these values for highest quality hash distribution.

**Comment by rymurr** [comment]
as per discussion moved L1 id map to 43 and reverted parent list

**Comment by rymurr** [comment]
@jacques-n this is failing at `ITDynamoVersionStore.mergeNoConflict` line 117. It fails when `L1.SIZE=43` but not with any of 36,41,42,44-53 or 151

**Comment by rymurr** [comment]
The problem described above is because for 43 L2s the two commits in the failing test both have changes for L2 number 20. So L2 number 20 has changed on both branches in the merge.The number 43 isn't special on its own its just the only number of bins that unluckily hashes a table into the same L2 tree. 

I think that the underlying problem is in the way we handle the commits array in a Ref...will now look at what could be the problem there. Working theory is that the commits array should be cleared before a merge...

**Comment by rymurr** [comment]
Well I think have narrowed it down to https://github.com/projectnessie/nessie/blob/main/versioned/tiered/src/main/java/com/dremio/nessie/versioned/impl/TieredVersionStore.java#L659

The intentions state how to get from (in the failing test) the empty commit to the merged state. They don't say how to get from the current HEAD to the merged state. I think the commit objects need to be re-written based on the new parent. Not yet sure how to do that. Probably have to create a Diff from current HEAD to now and use that as the intention.

**Comment by rymurr** [comment]
@jacques-n this should be ready to go now. The intention log is now written with the correct base commit.

**Comment by jacques-n** [comment]
The patch looks good. Any ideas for a test?

**Review by jacques-n — APPROVED** [review]

**Comment by jacques-n** [comment]
Merging for 0.3. Can you open follow-on issue for test?

**Pull request merged**
