### PR TITLE
Initial skeleton of RocksDB store

### PR DESCRIPTION
**Pull request by kylep-dremio**
Note that some this is intended for an early look, some unit tests will fail as putIfAbsent is not implemented.

Based upon the move of the generic store tests PR, so there the changes from that PR represented here as well.

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/567)

### CODE REVIEW

**Comment by rymurr** [comment]
Hey @kylep-dremio are the changes to the mongo store related to the rocksdb addition?

**Review by kylep-dremio — COMMENTED** [review]
@rymurr the Mongo changes should be (are) removed - they should be ignored.

> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/567#-:-MOmy2lP09qMnxvzO1WK:b2u56hc)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @jacques-n)

___
*[pom.xml, line 483 at r1](https://reviewable.io/reviews/projectnessie/nessie/567#-MOcJGAWxGhFCAfuMKqR-r1-483:-MOmy7HqBsc1I1lmq2tb:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/0c3fef637d7f18661679142871735d5c8fd4a507/pom.xml#L483)):*
<details><summary><i>Previously, jacques-n (Jacques Nadeau) wrote…</i></summary><blockquote>

Why the addition of Kryo? I think we should avoid Kryo for persistent serialization. In general, it is too hard to maintain compatibility. I suggest we use protobuf.
</blockquote></details>

Done.

**Review by laurentgo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/567)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @jacques-n and @kylep-dremio)

___
*[pom.xml, line 141 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOn7F5K4sGBBdYhZ2vH:-MOn7F5K4sGBBdYhZ2vI:b-ofl9ho) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/pom.xml#L141)):*
> ```XML
>     <mongodb.version>4.1.1</mongodb.version>
>     <prometheus.version>0.9.0</prometheus.version>
>     <rocksdb.version>5.14.2</rocksdb.version>
> ```

that is quite old, like July 2018 old...
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 76 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOn9sUe3LPSKRSlkz4a:-MOn9sUe3LPSKRSlkz4b:b2uqfvm) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L76)):*
> ```Java
>   static {
>     RocksDB.loadLibrary();
>     COLUMN_FAMILIES = ImmutableList.<byte[]>builder()
> ```

It is possible to avoid creating an intermediate `List`...   
```
     Stream.concat(Stream.of(RocksDB.DEFAULT_COLUMN_FAMILY), Arrays.stream(ValueType.values()).map(v -> v.name().getBytes(UTF_8)).collect(ImmutableList.toImmutableList());
   ```
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 106 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOnDkIk4XRwILaE7dP6:-MOnDkIk4XRwILaE7dP7:b-bjhonr) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L106)):*
> ```Java
>         rocksDB = RocksDB.open(dbOptions, dbPath, columnFamilies, columnFamilyHandles);
>         valueTypeToColumnFamily = IntStream.rangeClosed(1, ValueType.values().length).boxed().collect(
>             Collectors.toMap(k -> ValueType.values()[k - 1], columnFamilyHandles::get));
> ```

you can use `ImmutableMap.toImmutableMap` to get something immutable...
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 127 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOnBSaD82IPyN-6i8rk:-MOnBSaD82IPyN-6i8rl:b-537uut) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L127)):*
> ```Java
>   @Override
>   public void close() {
>     if (null != rocksDB) {
> ```

not set to null (so I guess it might be possible to try to flush a closed rocksdb)
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 162 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOnESiQEPHpcJbaOw3k:-MOnESiQEPHpcJbaOw3l:b-21z9z5) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L162)):*
> ```Java
>       final Map<byte[], byte[]> reads;
>       try {
>         reads = rocksDB.multiGet(columnFamilies, keys);
> ```

method got deprecated in recent versions of rocksdb
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 195 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOnEjsb6pYI5jnO2gcL:-MOnEjsb6pYI5jnO2gcM:b-qe97gf) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L195)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     if (conditionUnAliased.isPresent()) {
>       throw new UnsupportedOperationException("ConditionExpressions are not supported with RocksDB yet.");
>     }
> 

In a more functional style (no need to change, more fyi)
> ```
</details>

   conditionUnAliased.ifPresent(() -> throw new UnsupportedOperationException("ConditionExpressions are not supported with RocksDB yet.")); 
   ```
```

**Review by kylep-dremio — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/567)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @jacques-n and @laurentgo)

___
*[pom.xml, line 141 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOn7F5K4sGBBdYhZ2vH:-MOoZH1E4QR-SmN7_JCX:br0hgc8) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/pom.xml#L141)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

that is quite old, like July 2018 old...
</blockquote></details>

It was originally aligned to match what was used in Dremio, but updated to latest.
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 76 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOn9sUe3LPSKRSlkz4a:-MOoZKc3A5ipaidkiHox:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L76)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

It is possible to avoid creating an intermediate `List`...   
```
     Stream.concat(Stream.of(RocksDB.DEFAULT_COLUMN_FAMILY), Arrays.stream(ValueType.values()).map(v -> v.name().getBytes(UTF_8)).collect(ImmutableList.toImmutableList());
   ```
</blockquote></details>

Done.
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 106 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOnDkIk4XRwILaE7dP6:-MOoZLFR7IJtuPj3k1rs:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L106)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

you can use `ImmutableMap.toImmutableMap` to get something immutable...
</blockquote></details>

Done.
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 127 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOnBSaD82IPyN-6i8rk:-MOoZMEa2oxy6vOnKiWw:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L127)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

not set to null (so I guess it might be possible to try to flush a closed rocksdb)
</blockquote></details>

Done.
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 162 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOnESiQEPHpcJbaOw3k:-MOoZMp-4Vft1PO8f1Sn:b-93jza8) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L162)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

method got deprecated in recent versions of rocksdb
</blockquote></details>

Updated for multiGetAsList.
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 195 at r3](https://reviewable.io/reviews/projectnessie/nessie/567#-MOnEjsb6pYI5jnO2gcL:-MOoZP077Bg6fwbAukoe:bwygxsx) ([raw file](https://github.com/projectnessie/nessie/blob/edb8404a2bdd64dd219764ed3e7b187e67c6e8f0/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L195)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

> ```
>     if (conditionUnAliased.isPresent()) {
>       throw new UnsupportedOperationException("ConditionExpressions are not supported with RocksDB yet.");
>     }
> 

In a more functional style (no need to change, more fyi)
   ```
   conditionUnAliased.ifPresent(() -> throw new UnsupportedOperationException("ConditionExpressions are not supported with RocksDB yet.")); 
   ```
</blockquote></details>

Noted.

**Review by laurentgo — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r1, 1 of 13 files at r2, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/567)* status: 4 of 14 files reviewed, 4 unresolved discussions (waiting on @jacques-n and @kylep-dremio)

___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 152 at r4](https://reviewable.io/reviews/projectnessie/nessie/567#-MOqfqtJ1hqEaQ5JLYlr:-MOqfqtJ1hqEaQ5JLYls:b98lr5j) ([raw file](https://github.com/projectnessie/nessie/blob/7f53c6c500e30d960f322db1a1c0e2d95412f39f/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L152)):*
> ```Java
>       }
> 
>       final Map<Id, LoadOp<?>> idLoadOps = step.getOps().collect(Collectors.toMap(LoadOp::getId, Function.identity()));
> ```

as it seems everything is using lists (of same size), I wonder if the map is useful, except if we are looking for uniqueness (which seems to be guaranteed by LoadStep?)
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 175 at r4](https://reviewable.io/reviews/projectnessie/nessie/567#-MOqfXmt7AFTNdcjF1QF:-MOqfXmt7AFTNdcjF1QG:bu1yp1s) ([raw file](https://github.com/projectnessie/nessie/blob/7f53c6c500e30d960f322db1a1c0e2d95412f39f/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L175)):*
> ```Java
>         final LoadOp<?> loadOp = idLoadOps.get(Id.of(UnsafeByteOperations.unsafeWrap(keys.get(i))));
>         if (null == loadOp) {
>           throw new NotFoundException("Unable to find requested ref.");
> ```

is that even possible?
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 286 at r4](https://reviewable.io/reviews/projectnessie/nessie/567#-MOqhvda3Rfw_54jiqmg:-MOqhvda3Rfw_54jiqmh:bvfdvpn) ([raw file](https://github.com/projectnessie/nessie/blob/7f53c6c500e30d960f322db1a1c0e2d95412f39f/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L286)):*
> ```Java
>   @VisibleForTesting
>   void deleteAllData() {
>     for (ColumnFamilyHandle handle : valueTypeToColumnFamily.values()) {
> ```

There's a deleteRange method.

**Review by kylep-dremio — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/567)* status: 4 of 14 files reviewed, 4 unresolved discussions (waiting on @jacques-n and @laurentgo)

___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 152 at r4](https://reviewable.io/reviews/projectnessie/nessie/567#-MOqfqtJ1hqEaQ5JLYlr:-MOrGquP9ykE55kD9RbA:b596gfw) ([raw file](https://github.com/projectnessie/nessie/blob/7f53c6c500e30d960f322db1a1c0e2d95412f39f/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L152)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

as it seems everything is using lists (of same size), I wonder if the map is useful, except if we are looking for uniqueness (which seems to be guaranteed by LoadStep?)
</blockquote></details>

Looked at it again and removed this entirely.
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 175 at r4](https://reviewable.io/reviews/projectnessie/nessie/567#-MOqfXmt7AFTNdcjF1QF:-MOrEgp9DCPBRrAoBVeB:b-q5a5l4) ([raw file](https://github.com/projectnessie/nessie/blob/7f53c6c500e30d960f322db1a1c0e2d95412f39f/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L175)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

is that even possible?
</blockquote></details>

It shouldn't be. I pondered removing the check but left it in to be defensive.
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 286 at r4](https://reviewable.io/reviews/projectnessie/nessie/567#-MOqhvda3Rfw_54jiqmg:-MOrHlZjCKQuQKityjya:bil94xo) ([raw file](https://github.com/projectnessie/nessie/blob/7f53c6c500e30d960f322db1a1c0e2d95412f39f/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L286)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

There's a deleteRange method.
</blockquote></details>

There is, but it requires the min and max keys. I pondered it earlier but didn't pursue since it was only test related, but did a cheap workaround to use deleteRange.

**Review by laurentgo — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r1, 1 of 13 files at r2, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/567)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @jacques-n and @kylep-dremio)

___
*[versioned/rocksdb/src/main/proto/entity.proto, line 23 at r5](https://reviewable.io/reviews/projectnessie/nessie/567#-MOs3AFW6MoWI-g2qEFY:-MOs3AFW6MoWI-g2qEFZ:bv5acl6) ([raw file](https://github.com/projectnessie/nessie/blob/460ff8c47fe6b8131b61bb797f97d503223c17e0/versioned/rocksdb/src/main/proto/entity.proto#L23)):*
> ```protobuf
> option java_generate_equals_and_hash = true;
> 
> message List {
> ```

for clarity, let's call it EntityList (and EntityMap)
___
*[versioned/rocksdb/src/main/proto/entity.proto, line 32 at r5](https://reviewable.io/reviews/projectnessie/nessie/567#-MOs2k_W6CtKpssTr6hs:-MOs2k_W6CtKpssTr6ht:b-wd5rp2) ([raw file](https://github.com/projectnessie/nessie/blob/460ff8c47fe6b8131b61bb797f97d503223c17e0/versioned/rocksdb/src/main/proto/entity.proto#L32)):*
> ```protobuf
> 
> message Entity {
>   int32 type = 1;
> ```

I don't think you need type if using oneOf?
___
*[versioned/rocksdb/src/test/java/com/dremio/nessie/versioned/store/rocksdb/TestRocksDBStore.java, line 31 at r5](https://reviewable.io/reviews/projectnessie/nessie/567#-MOs3dBX-8Xnl_xTXaGX:-MOs3dBX-8Xnl_xTXaGY:b-tvys7z) ([raw file](https://github.com/projectnessie/nessie/blob/460ff8c47fe6b8131b61bb797f97d503223c17e0/versioned/rocksdb/src/test/java/com/dremio/nessie/versioned/store/rocksdb/TestRocksDBStore.java#L31)):*
> ```Java
> @TestInstance(TestInstance.Lifecycle.PER_CLASS)
> class TestRocksDBStore extends AbstractTestStore<RocksDBStore> {
>   private static final String DB_PATH = "/tmp/db";
> ```

let's use a random path (which should be easy to get thanks to junit)
___
*[versioned/tiered-tests/pom.xml, line 69 at r5](https://reviewable.io/reviews/projectnessie/nessie/567#-MOs4G2rDIpGoz6paxp1:-MOs4G2rDIpGoz6paxp2:b-gp0366) ([raw file](https://github.com/projectnessie/nessie/blob/460ff8c47fe6b8131b61bb797f97d503223c17e0/versioned/tiered-tests/pom.xml#L69)):*
> ```XML
>           <execution>
>             <goals>
>               <goal>integration-test</goal>
> ```

are there any test to be run in this module?
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 286 at r4](https://reviewable.io/reviews/projectnessie/nessie/567#-MOqhvda3Rfw_54jiqmg:-MOs2-PK9NPBopmszTXU:b5vfjdf) ([raw file](https://github.com/projectnessie/nessie/blob/7f53c6c500e30d960f322db1a1c0e2d95412f39f/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L286)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

There is, but it requires the min and max keys. I pondered it earlier but didn't pursue since it was only test related, but did a cheap workaround to use deleteRange.
</blockquote></details>

also, it looks like max is excluded :)

**Review by kylep-dremio — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/567)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @jacques-n and @laurentgo)

___
*[versioned/rocksdb/src/main/proto/entity.proto, line 23 at r5](https://reviewable.io/reviews/projectnessie/nessie/567#-MOs3AFW6MoWI-g2qEFY:-MOxi-Co7g3pUtOBXvNf:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/460ff8c47fe6b8131b61bb797f97d503223c17e0/versioned/rocksdb/src/main/proto/entity.proto#L23)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

for clarity, let's call it EntityList (and EntityMap)
</blockquote></details>

Done.
___
*[versioned/rocksdb/src/main/proto/entity.proto, line 32 at r5](https://reviewable.io/reviews/projectnessie/nessie/567#-MOs2k_W6CtKpssTr6hs:-MOxj-H44pXxgVRPJcY8:bvols1l) ([raw file](https://github.com/projectnessie/nessie/blob/460ff8c47fe6b8131b61bb797f97d503223c17e0/versioned/rocksdb/src/main/proto/entity.proto#L32)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I don't think you need type if using oneOf?
</blockquote></details>

You're right, didn't know about that...much nicer.
___
*[versioned/rocksdb/src/test/java/com/dremio/nessie/versioned/store/rocksdb/TestRocksDBStore.java, line 31 at r5](https://reviewable.io/reviews/projectnessie/nessie/567#-MOs3dBX-8Xnl_xTXaGX:-MOxkgEq0Ey2EhC7Pe_C:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/460ff8c47fe6b8131b61bb797f97d503223c17e0/versioned/rocksdb/src/test/java/com/dremio/nessie/versioned/store/rocksdb/TestRocksDBStore.java#L31)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

let's use a random path (which should be easy to get thanks to junit)
</blockquote></details>

Done.
___
*[versioned/tiered-tests/pom.xml, line 69 at r5](https://reviewable.io/reviews/projectnessie/nessie/567#-MOs4G2rDIpGoz6paxp1:-MOxkmPBE0jHbC5kYDxC:b-90a4em) ([raw file](https://github.com/projectnessie/nessie/blob/460ff8c47fe6b8131b61bb797f97d503223c17e0/versioned/tiered-tests/pom.xml#L69)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

are there any test to be run in this module?
</blockquote></details>

Good catch - at this point no.
___
*[versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 286 at r4](https://reviewable.io/reviews/projectnessie/nessie/567#-MOqhvda3Rfw_54jiqmg:-MOxjb5P5JoU9uC6eH8K:bs2eaea) ([raw file](https://github.com/projectnessie/nessie/blob/7f53c6c500e30d960f322db1a1c0e2d95412f39f/versioned/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L286)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

also, it looks like max is excluded :)
</blockquote></details>

Well that's just annoying...and there doesn't seem to be a way to make it inclusive.

**Review by laurentgo — COMMENTED** [review]
> Reviewed 2 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/567)* status: 8 of 14 files reviewed, 1 unresolved discussion (waiting on @jacques-n and @laurentgo)

**Comment by kylep-dremio** [comment]
Closing for the moment as this is undergoing refactoring and will not pass for a while.

**Pull request closed without merging**
