### PR TITLE
Remove deprecated `HttpClientBuilder`

### PR DESCRIPTION
**Pull request by snazy**
`HttpClientBuilder` has been deprecated for removal for a while and it is now safe to remove it. The functionality has been fully migrated to `NessieClientBuilder`.

### CODE REVIEW

**Comment by adutra** [comment]
I still see it used in Trino FYI:

https://github.com/trinodb/trino/blob/b2c4fc8f1525722d94ccfd5cbce85019cf403ed4/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java#L50

**Comment by ajantha-bhat** [comment]
> I still see it used in Trino FYI:

I know. We will remove in the next version bump time. 

Trino side PR movement is slow. Still https://github.com/trinodb/trino/pull/19524 is not merged.

**Comment by ajantha-bhat** [comment]
@adutra: Raised a WIP PR at Trino side based on Iceberg snapshot release
https://github.com/trinodb/trino/pull/20308

Once, Iceberg new version is released, I will rebase.

**Comment by snazy** [comment]
Requires: https://github.com/projectnessie/query-engine-integration-tests/pull/587

**Review by dimas-b — APPROVED** [review]

**Pull request merged**
