### PR TITLE
Add tracing to our http-client, make NessieClient an interface

### LINKED ISSUE #643: Add tracing back into client
With the removal of JAX-RS we have lost the automatic tracing feature for the clilent. We should add it back in and make it an optional switch for clients.

### PR DESCRIPTION
**Pull request by snazy**
Adds the OpenTracing/OpenTracing/Jaeger HTTP header(s) required for distributed tracing to requests sent by our HTTP client.

Refactors `NessieClient` to an interface, adds a builder, because there were now too many parameters/options.

Renames the term "path" used as the uri for the Nessie server to "uri" and also use the type `java.net.URI` for it.

Fixes #643

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835)

### CODE REVIEW

**Comment by rymurr** [comment]
I think we should add some docs and options here:

options:
* turn on/off
* how to handle if no active span
* create and populate a span

Right now we are adding a hidden and undocumented feature to the client and its kinda useless outside of perf testing.

**Review by laurentgo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @rymurr and @snazy)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/835#-MTkj8wL4R8IsLAiacUn:-MTkj8wL4R8IsLAiacUo:b-ch3qrj) (no related file):*
I'm confused by what the patch does. From how I interpret the code I see 2 problems:
* active span is checked when the client is created, not when the request is sent. But the caller might be using different spans between calls, which means nessie server calls would be linked to the wrong client context
* there's no child span being created for each nessie request, which seems an important thing to have

I'm also confused to see how this code can compile

---
___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 97 at r1](https://reviewable.io/reviews/projectnessie/nessie/835#-MTki7IF78lzect-T-Xo:-MTki7IG8gaFMj8AUFJg:b-4c0dj3) ([raw file](https://github.com/projectnessie/nessie/blob/5bf58d59ad230d3e57b3a9e8d697d90e1c21d5f6/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L97)):*
> ```Java
>     try {
>       TracingConfigurer.addTracing(httpClient);
>     } catch (Error | Exception e) {
> ```

You could just use `Throwable` for the same result, no?

But I think this is quite dangerous to catch anything, even possibly unrecoverable exceptions, and simply log about it. Why not catch `NoClassDefFoundError` or `LinkageError`?

**Review by snazy — COMMENTED** [review]
> how to handle if no active span

This should IMO be a decision of the caller of the Nessie API. If you do not have tracing enabled on the client side, the server will start the HTTP request, if tracing is enabled on the server side and the tracing probability triggers. So it doesn't add any value to _unconditionally_ start a span on the client side. On the client side, you probably want more information like the Spark job name, task id, etc.

Anyway, I've made the tracing on the client side configurable. Adding a new `boolean` parameter to all existing static methods felt weird, so I've refactored it to a builder-pattern for the NessieClient. The "enable tracing" behavior is also a bit now: If you enable it, the dependencies must be present.

> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835#-:-MTp7a60-CISN6ifTG12:b-n5htwc)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/835#-MTkj8wL4R8IsLAiacUn:-MTp6Iq01gSGud_gUcgI:b-bdju7f) (no related file):*
> active span is checked when the client is created

No, it's checked for each request. See the `RequestFilter` implementation lambda `httpClient.register((RequestFilter) context -> {`.

---

**Review by snazy — COMMENTED** [review]
As discussed offline, I've refactored `NessieClient` to be an interface.

Haven't added tests for that yet, but will add some tests tomorrow.

> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835#-:-MTq_XCODjZpNSMl8vM2:b2nz5mj)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

**Review by snazy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 97 at r1](https://reviewable.io/reviews/projectnessie/nessie/835#-MTki7IF78lzect-T-Xo:-MTq_jDh28MNKcdbqicm:b35xqxo) ([raw file](https://github.com/projectnessie/nessie/blob/5bf58d59ad230d3e57b3a9e8d697d90e1c21d5f6/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L97)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

You could just use `Throwable` for the same result, no?

But I think this is quite dangerous to catch anything, even possibly unrecoverable exceptions, and simply log about it. Why not catch `NoClassDefFoundError` or `LinkageError`?
</blockquote></details>

No longer needed ;)

**Review by rymurr — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 7 of 14 files at r2, 16 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835)* status: 24 of 25 files reviewed, 3 unresolved discussions (waiting on @laurentgo and @snazy)

___
*[clients/client/src/main/java/org/projectnessie/client/NessieConfigConstants.java, line 25 at r3](https://reviewable.io/reviews/projectnessie/nessie/835#-MTumPn75mzK9lM0yFtc:-MTumPn75mzK9lM0yFtd:b-vg0y43) ([raw file](https://github.com/projectnessie/nessie/blob/cbefb7a5112a45494924b4ca8534c6d83a55427c/clients/client/src/main/java/org/projectnessie/client/NessieConfigConstants.java#L25)):*
> ```Java
>    * Config property name ({@value #CONF_NESSIE_URL}) for the Nessie service URL.
>    */
>   public static final String CONF_NESSIE_URL = "nessie.url";
> ```

could you change this to uri too?

**Review by rymurr — DISMISSED** [review]

**Review by laurentgo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r2, 6 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835)* status: 25 of 26 files reviewed, 3 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 125 at r3](https://reviewable.io/reviews/projectnessie/nessie/835#-MTvDWMZAZ1QFEw2KDIu:-MTvDWMZAZ1QFEw2KDIv:b-6yj92e) ([raw file](https://github.com/projectnessie/nessie/blob/cbefb7a5112a45494924b4ca8534c6d83a55427c/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L125)):*
> ```Java
>      */
>     public Builder withUri(String uri) {
>       this.uri = uri;
> ```

should we accept URI, or confirm it is an URI?

**Review by snazy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835)* status: 13 of 30 files reviewed, 3 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 125 at r3](https://reviewable.io/reviews/projectnessie/nessie/835#-MTvDWMZAZ1QFEw2KDIu:-MTvvEkcEMmLyWWii7AT:b-yq2xmh) ([raw file](https://github.com/projectnessie/nessie/blob/cbefb7a5112a45494924b4ca8534c6d83a55427c/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L125)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

should we accept URI, or confirm it is an URI?
</blockquote></details>

`URI` feels much safer than `String`. It actually simplifies a few places. Changed that mostly everywhere.
___
*[clients/client/src/main/java/org/projectnessie/client/NessieConfigConstants.java, line 25 at r3](https://reviewable.io/reviews/projectnessie/nessie/835#-MTumPn75mzK9lM0yFtc:-MTvvPU2EtsARDZsh0RI:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/cbefb7a5112a45494924b4ca8534c6d83a55427c/clients/client/src/main/java/org/projectnessie/client/NessieConfigConstants.java#L25)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

could you change this to uri too?
</blockquote></details>

Done.

**Comment by rymurr** [comment]
I can't see the whole patch at the moment but can we ensure we have a
builder method that still takes string and creates a Uri internally? The
iceberg client is created from a string map passed in with spark etc.
Etc... Just kinda a pain to add a layer for the Uri conversion

**Comment by snazy** [comment]
You can still create the client from a "string-to-string map" using the "standard property names" defined in `NessieConfigConstants`. But I've added a `withUri(String)`.

**Review by laurentgo — COMMENTED** [review]
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835)* status: 13 of 30 files reviewed, 1 unresolved discussion (waiting on @rymurr)

___
*[clients/client/src/main/java/org/projectnessie/client/NessieHttpClient.java, line 95 at r7](https://reviewable.io/reviews/projectnessie/nessie/835#-MU7R8KO1wWtmpl-Fv-0:-MU7R8KO1wWtmpl-Fv-1:b-1g5gtm) ([raw file](https://github.com/projectnessie/nessie/blob/cbe3d357d3e0f91e7e019faee6870d7d0d03e4a3/clients/client/src/main/java/org/projectnessie/client/NessieHttpClient.java#L95)):*
> ```Java
>             if (responseContext != null) {
>               try {
>                 scope.span().setTag("http.status", responseContext.getResponseCode().getCode());
> ```

fyi: opentracing uses `http.status_code`: https://opentracing.io/specification/conventions/
___
*[clients/client/src/main/java/org/projectnessie/client/NessieHttpClient.java, line 109 at r7](https://reviewable.io/reviews/projectnessie/nessie/835#-MU7ROlQDtZMmQxc-JTj:-MU7ROlQDtZMmQxc-JTk:bzc6oju) ([raw file](https://github.com/projectnessie/nessie/blob/cbe3d357d3e0f91e7e019faee6870d7d0d03e4a3/clients/client/src/main/java/org/projectnessie/client/NessieHttpClient.java#L109)):*
> ```Java
>           });
> 
>           scope.span().setTag("http.uri", context.getUri().toString());
> ```

you might want to add `http.method` too

**Review by snazy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835)* status: 13 of 30 files reviewed, 1 unresolved discussion (waiting on @rymurr)

___
*[clients/client/src/main/java/org/projectnessie/client/NessieHttpClient.java, line 95 at r7](https://reviewable.io/reviews/projectnessie/nessie/835#-MU7R8KO1wWtmpl-Fv-0:-MU7kuB27fVFqlI01c1-:bb7f2mf) ([raw file](https://github.com/projectnessie/nessie/blob/cbe3d357d3e0f91e7e019faee6870d7d0d03e4a3/clients/client/src/main/java/org/projectnessie/client/NessieHttpClient.java#L95)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

fyi: opentracing uses `http.status_code`: https://opentracing.io/specification/conventions/
</blockquote></details>

done
___
*[clients/client/src/main/java/org/projectnessie/client/NessieHttpClient.java, line 109 at r7](https://reviewable.io/reviews/projectnessie/nessie/835#-MU7ROlQDtZMmQxc-JTj:-MU7kvHJAYSlOng89yj4:bb7f2mf) ([raw file](https://github.com/projectnessie/nessie/blob/cbe3d357d3e0f91e7e019faee6870d7d0d03e4a3/clients/client/src/main/java/org/projectnessie/client/NessieHttpClient.java#L109)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

you might want to add `http.method` too
</blockquote></details>

done

**Review by laurentgo — APPROVED** [review]
> Reviewed 13 of 17 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/835)* status: all files reviewed, 1 unresolved discussion (waiting on @rymurr)

**Pull request merged**
