### PR TITLE
switch to gradle java toolchains

### PR DESCRIPTION
**Pull request by XN137**

### CODE REVIEW

**Comment by snazy** [comment]
Let's be careful with toolchains, it's sadly not as easy as it sounds.

**Comment by XN137** [comment]
i am mostly using this PR to run some experiments atm

what specific limitations/problems are you aware of with toolchains that we cant deal with?

**Comment by snazy** [comment]
* Gradle downloading a JDK
* Gradle using the wrong JDK (new Java version CI runs)
* And something else I don't recall

**Comment by XN137** [comment]
closing since this was mostly replaced with https://github.com/projectnessie/nessie/pull/6726 ...

i guess the remaining difference can only be properly cleaned up once we target java 11 bytecode for non-client code parts

**Pull request closed without merging**
