### PR TITLE
switch to micrometer

### PR DESCRIPTION
**Pull request by rymurr**
I have added prometheus but there are plenty of options:

https://micrometer.io/docs

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/368)

### CODE REVIEW

**Review by laurentgo — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/368)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @rymurr)

___
*[backends/dynamodb/src/main/java/com/dremio/nessie/backend/dynamodb/AbstractEntityDynamoDbBackend.java, line 239 at r1](https://reviewable.io/reviews/projectnessie/nessie/368#-MK5ZpVw1sq7j-7v7o6d:-MK5ZpVw1sq7j-7v7o6e:b-s1oqxg) ([raw file](https://github.com/projectnessie/nessie/blob/60bd8c6bb4fa41b2d6fe9ed8593f60179af74952/backends/dynamodb/src/main/java/com/dremio/nessie/backend/dynamodb/AbstractEntityDynamoDbBackend.java#L239)):*
> ```Java
> 
>     private MetricsCloseable(String name) {
>       histogram = Timer.builder("dynamodb-function")
> ```

histogram and counter can (should?) be initialized in DynamoMetrics so only registered once.
MetricsCloseable can be made into an inner class (or an anonymous lambda)

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/368)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @laurentgo)

___
*[backends/dynamodb/src/main/java/com/dremio/nessie/backend/dynamodb/AbstractEntityDynamoDbBackend.java, line 239 at r1](https://reviewable.io/reviews/projectnessie/nessie/368#-MK5ZpVw1sq7j-7v7o6d:-MKAQsfiEaEECs5RgSTq:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/60bd8c6bb4fa41b2d6fe9ed8593f60179af74952/backends/dynamodb/src/main/java/com/dremio/nessie/backend/dynamodb/AbstractEntityDynamoDbBackend.java#L239)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

histogram and counter can (should?) be initialized in DynamoMetrics so only registered once.
MetricsCloseable can be made into an inner class (or an anonymous lambda)
</blockquote></details>

Done.

**Review by laurentgo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/368)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @laurentgo)

___
*[backends/dynamodb/src/main/java/com/dremio/nessie/backend/dynamodb/AbstractEntityDynamoDbBackend.java, line 248 at r2](https://reviewable.io/reviews/projectnessie/nessie/368#-MKAtyoE1OtX9mZTOPVv:-MKAtyoFAhqKsa8IQT3s:b910b2b) ([raw file](https://github.com/projectnessie/nessie/blob/5b227ee01850b3651be897325191d72bebb3aa6e/backends/dynamodb/src/main/java/com/dremio/nessie/backend/dynamodb/AbstractEntityDynamoDbBackend.java#L248)):*
> ```Java
>    * used to avoid having to catch Exception that can't be thrown in close method.
>    */
>   private interface ExceptionFreeAutoClosable extends AutoCloseable {
> ```

Maybe `Closeable` (`java.io.Closeable` is not imported) or `Timer` are more concise/more descriptive?
Should probably add `@FunctionalInterface` annotation too

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/368)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @laurentgo)

___
*[backends/dynamodb/src/main/java/com/dremio/nessie/backend/dynamodb/AbstractEntityDynamoDbBackend.java, line 248 at r2](https://reviewable.io/reviews/projectnessie/nessie/368#-MKAtyoE1OtX9mZTOPVv:-MKAvzhV1tA8iwxsSSQP:b-vdjepr) ([raw file](https://github.com/projectnessie/nessie/blob/5b227ee01850b3651be897325191d72bebb3aa6e/backends/dynamodb/src/main/java/com/dremio/nessie/backend/dynamodb/AbstractEntityDynamoDbBackend.java#L248)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

Maybe `Closeable` (`java.io.Closeable` is not imported) or `Timer` are more concise/more descriptive?
Should probably add `@FunctionalInterface` annotation too 
</blockquote></details>

cleaned it up a bit

**Comment by laurentgo** [comment]
Merging the change (the code coverage change is negligeable)

**Pull request merged**
