### PR TITLE
Remove metrics MP dependency

### PR DESCRIPTION
**Pull request by laurentgo**
Remove metrics MP from services module, along with redundant
JAX-RS/OpenAPI annotations.

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/471)

### CODE REVIEW

**Review by laurentgo — COMMENTED** [review]
Should probably wait before merging: looks like there's automatic registration of JAX-RS resources, and only Vert.x paths are automatically recorded.

**Review by rymurr — APPROVED** [review]
Not sure how I missed these. I think they would duplicate the ones that are generated by vert.x

I believe that the generated ones are only shown once the particular endpoint has been called once.

**Comment by rymurr** [comment]
Just ran a test and all web associated endpoints have (rather good) metrics. Note they only appear after the first call to that specific endpoint

The metrics show {max,count,sum} for each {endpoint, status, method} tuple. eg:

It would be nice if we could add median some percentiles though.
```
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/trees/tree",} 6.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/trees/tree",} 0.183501336
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/favicon.ico",} 5.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/favicon.ico",} 0.038488092
http_server_requests_seconds_count{method="GET",outcome="CLIENT_ERROR",status="404",uri="NOT_FOUND",} 1.0
http_server_requests_seconds_sum{method="GET",outcome="CLIENT_ERROR",status="404",uri="NOT_FOUND",} 0.028785987
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/config",} 1.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/config",} 0.027142632
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/metrics",} 4.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/metrics",} 0.144775524
http_server_requests_seconds_max{method="GET",outcome="SUCCESS",status="200",uri="/trees/tree",} 0.153592533
http_server_requests_seconds_max{method="GET",outcome="SUCCESS",status="200",uri="/favicon.ico",} 0.002999471
http_server_requests_seconds_max{method="GET",outcome="CLIENT_ERROR",status="404",uri="NOT_FOUND",} 0.028785987
http_server_requests_seconds_max{method="GET",outcome="SUCCESS",status="200",uri="/config",} 0.027142632
http_server_requests_seconds_max{method="GET",outcome="SUCCESS",status="200",uri="/metrics",} 0.02714496
```

**Comment by laurentgo** [comment]
@rymurr was the metrics produced with this patch? I do not have any of the REST API metrics locally.

**Comment by rymurr** [comment]
yessir!

**Comment by laurentgo** [comment]
Ok, works locally for me too, I just hit a bug with the UI which prevented the REST endpoints to be hit.

**Pull request merged**
