### PR TITLE
Update hash-check rule to allow hex representation of 3..32 bytes

### PR DESCRIPTION
**Pull request by snazy**
Was 8..32 bytes before.

### CODE REVIEW

**Review by nastra — COMMENTED** [review]
not sure I understand the reasoning behind this change, can you elaborate?

**Comment by snazy** [comment]
Thinking of abbreviated commit hashes - repos likely start with a quite short abbreviated hash, so 6 hex digits feels a bit nicer than a minimum of 16 hex digits.
I don't insist on this changed - just stumbled upon this.

**Comment by nastra** [comment]
> Thinking of abbreviated commit hashes - repos likely start with a quite short abbreviated hash, so 6 hex digits feels a bit nicer than a minimum of 16 hex digits. I don't insist on this changed - just stumbled upon this.

just wondering whether we should have at the very least a length of 7 or 8 instead of 6? Git uses 8 for abbreviated hashes

**Comment by snazy** [comment]
I'm okay with 8

**Comment by dimas-b** [comment]
git is dynamic AFAIK, it will use more digits if it expected higher clash probability

**Review by dimas-b — APPROVED** [review]

**Review by dimas-b — COMMENTED** [review]
~~Actual change LGTM, but I'm not sure I understand the commit message :) the `4..32` and the `Was 8..32 bytes before` parts... the numbers do not seem to match code diffs~~

nvm, got it

**Pull request merged**
