### PR TITLE
upgrade workflows to ubuntu-22.04

### PR DESCRIPTION
**Pull request by XN137**
the image is out of beta and planned to become `ubuntu-latest` later this year

### CODE REVIEW

**Comment by snazy** [comment]
Do the Nessie Quarkus native images built with/on the 22.04 GH runner work on older Linux distros?
I.e. build the Nessie Quarkus native image on Ubuntu 22.04, run it on Ubuntu 18.04.
IIRC there were issues a while ago, but it might be fine with the 22.04 GH runner, because the Quarkus native image's built in a container. But would be good to check.

**Comment by XN137** [comment]
did we give any strong support guarantees or why would we care about 18.04 still ? (it seems to go EOL next year)

imo even if it did break, users could just:
- stick to a previous nessie version
- upgrade their machines to 20.04 or 22.04 (which they should do anyway?)
- build their own images from source however they like

**Comment by snazy** [comment]
It is not about Ubuntu, it's about the libc version and e.g. current RH dsitros

**Comment by snazy** [comment]
@XN137 shall we get this one done?

**Comment by XN137** [comment]
i only did this because i thoughts it's simple and risk free.
if there is the risk of breaking things and requires extensive testing then since this is neither important nor urgent, i think we can just close this for now (until the version we are using goes EOL).

**Pull request closed without merging**
