### PR TITLE
test matrix for jackson

### PR DESCRIPTION
**Pull request by rymurr**
This PR adds a set of github actions to test various versions of Jackson against our Nessie Client. This is to test compatibility of the client with various versions of jackson found in downstream tools. This depends on #629

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/630)

### CODE REVIEW

**Review by snazy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/630)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @rymurr and @snazy)

___
*[.github/workflows/main.yml, line 123 at r1](https://reviewable.io/reviews/projectnessie/nessie/630#-MPmx0OYB4SL2FSadBXe:-MPmx0OYB4SL2FSadBXf:b-7ilvfu) ([raw file](https://github.com/projectnessie/nessie/blob/6948048d55e95bccacdb1c06a8fc24c794d62cbe/.github/workflows/main.yml#L123)):*
> ```YAML
>             target-library: Spark 2.4.4
>           - jackson-version: 2.10.0
>             target-library: Spark 3.0,1
> ```

typo?
___
*[.github/workflows/main.yml, line 129 at r1](https://reviewable.io/reviews/projectnessie/nessie/630#-MPn0WbZ9hA8ob_Iv5ud:-MPn0WbZ9hA8ob_Iv5ue:b-k3kvy7) ([raw file](https://github.com/projectnessie/nessie/blob/6948048d55e95bccacdb1c06a8fc24c794d62cbe/.github/workflows/main.yml#L129)):*
> ```YAML
>         uses: actions/setup-java@v1
>         with:
>           java-version: 11
> ```

Do all the Hive and Spark versions use Java 11?
___
*[.github/workflows/pull-request.yml, line 105 at r1](https://reviewable.io/reviews/projectnessie/nessie/630#-MPmx27-50JFazsakoAW:-MPmx27-50JFazsakoAX:b-7ilvfu) ([raw file](https://github.com/projectnessie/nessie/blob/6948048d55e95bccacdb1c06a8fc24c794d62cbe/.github/workflows/pull-request.yml#L105)):*
> ```YAML
>             target-library: Spark 2.4.4
>           - jackson-version: 2.10.0
>             target-library: Spark 3.0,1
> ```

typo?
___
*[.github/workflows/pull-request.yml, line 111 at r1](https://reviewable.io/reviews/projectnessie/nessie/630#-MPn0YF97KleBAkEG2OO:-MPn0YF97KleBAkEG2OP:b-k3kvy7) ([raw file](https://github.com/projectnessie/nessie/blob/6948048d55e95bccacdb1c06a8fc24c794d62cbe/.github/workflows/pull-request.yml#L111)):*
> ```YAML
>         uses: actions/setup-java@v1
>         with:
>           java-version: 11
> ```

Do all the Hive and Spark versions use Java 11?

**Comment by snazy** [comment]
Looks like an overall improvement to test-coverage for the http-client.
Not sure whether it's worth to add these integration-tests for every PR though.

I think, it needs to run all the REST-tests from the `nessie-quarkus` module using the various Jackson-versions for the client to get to "full confidence" and exercise all the Jackson things we're actually using for all the JSON (de)serialization.

**Review by rymurr — COMMENTED** [review]
Agreed re quarkus tests, the fancy annotations hven't been tested fully yet. This gives me comfort that at least the ObjectMapper and readers/writers can run. Maybe a job that uses the latest docker image and exercises the client endpoints can be added in the future.

Also, I agree w/ running on every PR. That was partially to ensure the job works (actions are hard to test!) I have now removed the PR 

> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/630#-:-MPnRZbYEpe_rIAysypG:bp9ttm6)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @snazy)

___
*[.github/workflows/main.yml, line 123 at r1](https://reviewable.io/reviews/projectnessie/nessie/630#-MPmx0OYB4SL2FSadBXe:-MPnR2uw6ffniJ3PYi9A:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/6948048d55e95bccacdb1c06a8fc24c794d62cbe/.github/workflows/main.yml#L123)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Done.
___
*[.github/workflows/main.yml, line 129 at r1](https://reviewable.io/reviews/projectnessie/nessie/630#-MPn0WbZ9hA8ob_Iv5ud:-MPnR3Mr3VDwYrsasOsw:b-y16n4h) ([raw file](https://github.com/projectnessie/nessie/blob/6948048d55e95bccacdb1c06a8fc24c794d62cbe/.github/workflows/main.yml#L129)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Do all the Hive and Spark versions use Java 11?
</blockquote></details>

you are right added an 8 job also
___
*[.github/workflows/pull-request.yml, line 105 at r1](https://reviewable.io/reviews/projectnessie/nessie/630#-MPmx27-50JFazsakoAW:-MPnRTYSEPay7axGZVEv:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/6948048d55e95bccacdb1c06a8fc24c794d62cbe/.github/workflows/pull-request.yml#L105)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Done.
___
*[.github/workflows/pull-request.yml, line 111 at r1](https://reviewable.io/reviews/projectnessie/nessie/630#-MPn0YF97KleBAkEG2OO:-MPnRUhV99qQ5LtFDgbd:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/6948048d55e95bccacdb1c06a8fc24c794d62cbe/.github/workflows/pull-request.yml#L111)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Do all the Hive and Spark versions use Java 11?
</blockquote></details>

Done.

**Review by snazy — APPROVED** [review]
+1

Can you open a new issue so the tasks to add the "proper client integration tests with the various jackson-versions" doesn't get lost?

**Pull request merged**
