### PR TITLE
WIP: run adapter concurrency tests many times over

### PR DESCRIPTION
**Pull request by dimas-b**
For #2026

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/2033)

### CODE REVIEW

**Review by snazy — COMMENTED** [review]
Um - CI takes nearly 80 minutes with this PR.
I don't mind running canary PR runs to figure out the issue, but object making CI slower than necessary.

**Comment by dimas-b** [comment]
I did not mean to merge this, just to run more tests in CI

**Comment by snazy** [comment]
Hint: you can update the `.github/workflows/pull-requests.yml` in the branch to your needs, if that helps.

**Comment by dimas-b** [comment]
See notes in #2026

**Pull request closed without merging**
