### PR TITLE
Reorganise routes

### PR DESCRIPTION
**Pull request by rymurr**

### CODE REVIEW

**Comment by snazy** [comment]
Haven't looked at the (many) changes in detail but started it locally.
Using `java -jar servers/quarkus-server/target/quarkus-app/quarkus-run.jar` + `java -jar tools/content-generator/target/nessie-content-generator-0.19.1-SNAPSHOT.jar generate`

The branch picker (the dropdown at the upper left) doesn't seem to work as expected.
Examples:
* Click through the contents "folders", open the branch-picker - the link to the "main" branch points to the wrong path:
Screenshot from 2022-02-14 09-55-52
  and results in a "nothing to show"
Screenshot from 2022-02-14 09-57-36
* Similar from a content-object like this: 
Screenshot from 2022-02-14 09-59-01 clicking on "main" from the branch-picker shows
Screenshot from 2022-02-14 09-59-52 and the "Home" link on that page doesn't work (stays on the  not-found page).
* The link to "Commit history" from the "home" page shows no commits: Screenshot from 2022-02-14 10-01-32 -->
Screenshot from 2022-02-14 10-02-39
* The `<>` button on the commit listing page links to the wrong URL
Screenshot from 2022-02-14 10-04-12 and shows 
Screenshot from 2022-02-14 10-05-08 instead of 
Screenshot from 2022-02-14 10-05-24

**Comment by rymurr** [comment]
Thanks @snazy 

Issue 1 (changing branch at folder level) is fixed. bad refactor and now tested
Issue 2 (changing branch at content level) same as 1.
Issue 3 (not found navigation and back button acting funny)  ... misunderstanding of index routes. Fixed now.
Issue 4 (wrong url for commit history) is fixed. Again, bad refactor.
Issue 5 (view repo at this commit) had the wrong behaviour in the original code - it only showed the commit history, not the repo at the commit. Ive fixed it now to show the commit on the branch. My original patch didn't add the branch, now fixed.

**Comment by snazy** [comment]
* `org.projectnessie.server.filters.SinglePageAppRoutingFilter` needs to handle `/commits` - otherwise a "reload" of e.g. `http://localhost:19120/commits/main/` results in a HTTP/404
* From e.g. `http://localhost:19120/tree/branch-2022-02-15-10-21-57_0/`, the link to `Commit History` points to the default branch
* Can the branch picker select the currently used branch instead of the default branch?
* The link to `Commit History` is gone from the contents-view. Intentional? (from e.g. `http://localhost:19120/content/main/create-contents-2022-02-15-10-21-57/contents/0`)
* The Commit History page always shows the commits from the default branch - even from a page e.g. `http://localhost:19120/tree/branch-2022-02-15-10-21-57_1/`

**Comment by rymurr** [comment]
> * `org.projectnessie.server.filters.SinglePageAppRoutingFilter` needs to handle `/commits` - otherwise a "reload" of e.g. `http://localhost:19120/commits/main/` results in a HTTP/404

Fixed, thanks

> * From e.g. `http://localhost:19120/tree/branch-2022-02-15-10-21-57_0/`, the link to `Commit History` points to the default branch

Fixed, thanks. Same issue as below.

> * Can the branch picker select the currently used branch instead of the default branch?

Weird, fixed now. Deleted some legacy code which was hijacking the route

> * The link to `Commit History` is gone from the contents-view. Intentional? (from e.g. `http://localhost:19120/content/main/create-contents-2022-02-15-10-21-57/contents/0`)

This is the same behaviour as `0.18.0`. commit history is only shown on the front page

> * The Commit History page always shows the commits from the default branch - even from a page e.g. `http://localhost:19120/tree/branch-2022-02-15-10-21-57_1/`

also fixed...this is the same legacy code as the other 2 issues.

**Comment by snazy** [comment]
:partyparrot:

**Review by snazy — APPROVED** [review]

**Pull request merged**
