### PR TITLE
Add key range parameters to REST API v2

### LINKED ISSUE #5591: Add start/end key parameters to v2 API methods
With some incoming storage model improvements, Nessie can return results not only for a collection of fixed keys but also for key ranges.

Start/end key boundaries are meaningful in these `TreeApi` v2 methods:
* `getEntries`
* `getDiff`

Potentially later:
* `getReferences` (?)

Likely not happening soon:
* `getSeveralContents`
* `getMultipleContents`

### PR DESCRIPTION
**Pull request by dimas-b**
* In "diff" API

* In "get entries"

* New "get contents" endpoint for range queries

This is just an API-level change to reserve REST paths and query 
parameters. Server-side implementation to be done separately.

Closes #5591

### CODE REVIEW

**Comment by dimas-b** [comment]
@snazy : do you want range params for reference endpoints too?

**Comment by snazy** [comment]
> @snazy : do you want range params for reference endpoints too?

Yes, that would be good. It would also be nicer to the new storage stuff to change the `maxKey` parameter from _exclusive_ to _inclusive. We can technically encode a prefix-query with the min and max parameters:

* _from...to_ : `minKey` defines the start (inclusive) and `maxKey` the end (inclusive)
* _from_ : `minKey` defines the start (inclusive)
* _to_ : `maxKey` defines the end (inclusive)
* _prefix_ : `minKey == maxKey` define the _prefix_ for the returned keys. "min equal to max" doesn't really make sense for a query and should be performed via a point-query (get-content) - so we _could_ abuse this case. From a usability perspective if would probably make sense to have a separate parameter for this though.

**Comment by snazy** [comment]
Shall we continue on this one?
We can omit `New "get contents" endpoint for range queries` for now, but have range-queries for `getAllReferences`

**Comment by snazy** [comment]
Closing with its successor #6743

**Pull request closed without merging**
