### PR TITLE
Update UI to use TypeScript

### PR DESCRIPTION
**Pull request by jacques-n**
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/427)

### CODE REVIEW

**Review by rymurr — CHANGES_REQUESTED** [review]
> Reviewed 72 of 74 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/427)* status: all files reviewed, 3 unresolved discussions (waiting on @jacques-n and @laurentgo)

___
*[ui/src/utils/api/.openapi-generator-ignore, line 10 at r2](https://reviewable.io/reviews/projectnessie/nessie/427#-MLCXLLMDHenBs0hZxQ9:-MLCXLLMDHenBs0hZxQA:b-pgx88y) ([raw file](https://github.com/projectnessie/nessie/blob/952fb0c6eb3678950ae4cc0128a0f269887bc5de/ui/src/utils/api/.openapi-generator-ignore#L10)):*
> ```
> # You can make changes and tell OpenAPI Generator to ignore just this file by uncommenting the following line:
> #ApiClient.cs
> ```

does this file do anything? I suppose it might make sense that one day we will need one though
___
*[ui/src/utils/api/git_push.sh, line 4 at r2](https://reviewable.io/reviews/projectnessie/nessie/427#-MLCX_tRCiZS54zJlCzq:-MLCX_tRCiZS54zJlCzr:b-mchm1z) ([raw file](https://github.com/projectnessie/nessie/blob/952fb0c6eb3678950ae4cc0128a0f269887bc5de/ui/src/utils/api/git_push.sh#L4)):*
> ```Shell
> # ref: https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/
> #
> # Usage example: /bin/sh ./git_push.sh wing328 openapi-pestore-perl "minor update"
> ```

do we need this?
___
*[ui/src/react-app-env.d.ts, line 16 at r2](https://reviewable.io/reviews/projectnessie/nessie/427#-MLCV7M36MOh2ZDM3xmv:-MLCV7M36MOh2ZDM3xmw:b-yn76d) ([raw file](https://github.com/projectnessie/nessie/blob/952fb0c6eb3678950ae4cc0128a0f269887bc5de/ui/src/react-app-env.d.ts#L16)):*
> ```XML
>  * limitations under the License.
>  */
> /// <reference types="react-scripts" />
> ```

not a ts expert, what does this do?

**Comment by rymurr** [comment]
A few minor commets, overall looks good. TS makes it much nicer

**Review by jacques-n — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/427)* status: all files reviewed, 3 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[ui/src/utils/api/.openapi-generator-ignore, line 10 at r2](https://reviewable.io/reviews/projectnessie/nessie/427#-MLCXLLMDHenBs0hZxQ9:-MLUR7lTEBwxp18fowH_:b-rbcfoo) ([raw file](https://github.com/projectnessie/nessie/blob/952fb0c6eb3678950ae4cc0128a0f269887bc5de/ui/src/utils/api/.openapi-generator-ignore#L10)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

does this file do anything? I suppose it might make sense that one day we will need one though
</blockquote></details>

I removed this in r3.
___
*[ui/src/utils/api/git_push.sh, line 4 at r2](https://reviewable.io/reviews/projectnessie/nessie/427#-MLCX_tRCiZS54zJlCzq:-MLUR9KL6_tdWcS-oxrX:bd4jbz) ([raw file](https://github.com/projectnessie/nessie/blob/952fb0c6eb3678950ae4cc0128a0f269887bc5de/ui/src/utils/api/git_push.sh#L4)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

do we need this?
</blockquote></details>

I removed this in r3. Crazy all the code the files the api generator creates...
___
*[ui/src/react-app-env.d.ts, line 16 at r2](https://reviewable.io/reviews/projectnessie/nessie/427#-MLCV7M36MOh2ZDM3xmv:-MLUR5l1C75HqVQhJFw-:b-rbcfpj) ([raw file](https://github.com/projectnessie/nessie/blob/952fb0c6eb3678950ae4cc0128a0f269887bc5de/ui/src/react-app-env.d.ts#L16)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

not a ts expert, what does this do?
</blockquote></details>

I removed this in r2.

**Review by rymurr — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/427)* status: all files reviewed, 1 unresolved discussion (waiting on @jacques-n and @laurentgo)

___
*[ui/src/react-app-env.d.ts, line 16 at r2](https://reviewable.io/reviews/projectnessie/nessie/427#-MLCV7M36MOh2ZDM3xmv:-MLgnStUCm_8f67udzbu:bmsl8wf) ([raw file](https://github.com/projectnessie/nessie/blob/952fb0c6eb3678950ae4cc0128a0f269887bc5de/ui/src/react-app-env.d.ts#L16)):*
<details><summary><i>Previously, jacques-n (Jacques Nadeau) wrote…</i></summary><blockquote>

I removed this in r2.
</blockquote></details>

i still see `ui/src/eact-app-env.d.ts` in this revision (r3)

**Review by rymurr — APPROVED** [review]

**Comment by jacques-n** [comment]
RE react-app-env.d.ts: turns out that if we don't have this, build creates it and then it fails on license check. For now going to keep it.

**Review by rymurr — APPROVED** [review]

**Review by rymurr — APPROVED** [review]
Lgtm

**Pull request merged**
