### PR TITLE
Serialize NessieApi

### PR DESCRIPTION
**Pull request by ajantha-bhat**
to pass from spark driver to executor.

After changing bunch of classes to Serializable and making `SSLContext` and `ObjectMapper` transient because of below errors.

SSLContext:
`java.io.NotSerializableException: javax.net.ssl.SSLContext
`
ObjectMapper:
`Caused by: java.io.NotSerializableException: com.fasterxml.jackson.databind.jsontype.impl.TypeNameIdResolver
`
**Also modified GC spark code to send the nessie api from driver to executor and (close the API in driver)**

TODO: probably need to reconstruct SSLContext at executor by taking config, else HTTPS connections doesn't work.

### CODE REVIEW

**Comment by tomekl007** [comment]
Can you link corresponding spark changes?

**Comment by nastra** [comment]
TBH I don't really understand why we need to make all of those APIs serializable. Can you please elaborate and describe the actual problem you're facing?

**Comment by ajantha-bhat** [comment]
@nastra : please refer thread https://github.com/projectnessie/nessie/pull/3421#discussion_r836502224

I was just sending a api conf from driver to executor and building new instance. But because of spark lazy iterator, I couldn't free the api resources in negative scenarios. After lot of experimentation, decided that I don't create new instance in executor, I send from driver. But sending from driver to executor needs a serailizable instance.

**Comment by ajantha-bhat** [comment]
> Can you link corresponding spark changes?

Update the description, it is in the same PR, GC module spark code.

**Comment by nastra** [comment]
> @nastra : please refer thread [#3421 (comment)](https://github.com/projectnessie/nessie/pull/3421#discussion_r836502224)
> 
> I was just sending a api conf from driver to executor and building new instance of NessieAPI. But because of spark lazy iterator, I couldn't free the api resources in negative scenarios. After lot of experimentation, decided that I don't create new instance in executor, Instead I can send from driver and fee resource in driver after usage. But sending from driver to executor needs a serailizable instance.

I'm -1 on making the APIs serializable for solving the problem you're facing. We rather need to solve the actual root issue and not create workarounds

**Comment by tomekl007** [comment]
> > @nastra : please refer thread [#3421 (comment)](https://github.com/projectnessie/nessie/pull/3421#discussion_r836502224)
> > I was just sending a api conf from driver to executor and building new instance of NessieAPI. But because of spark lazy iterator, I couldn't free the api resources in negative scenarios. After lot of experimentation, decided that I don't create new instance in executor, Instead I can send from driver and fee resource in driver after usage. But sending from driver to executor needs a serailizable instance.
> 
> I'm -1 on making the APIs serializable for solving the problem you're facing. We rather need to solve the actual root issue and not create workarounds

@ajantha-bhat can you check if other, "spark friendly" HTTP clients are serializable as well? If they are, it means that's the proper solution for spark. And if someone will want to use our `NessieAPI` form Spark, they will hit the same problem, therefore making it serializable would be a reasonable choice.

**Comment by snazy** [comment]
I do not get what this change shall actually solves in which way.
We're talking about e.g. OS level resources here that need to be properly closed.

Definitely -1 on making the Nessie API serializable.

**Comment by ajantha-bhat** [comment]
> I do not get what this change shall actually solves in which way.

this solves the problem of cleaning up resources of NessieAPI at executor by avoiding creating new instance in executor and pass the instance from driver. Because the original object reside in driver, driver is closing the resources.

**Pull request closed without merging**
