### PR TITLE
Codecov report change

### PR DESCRIPTION
**Pull request by jacques-n**
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/256)

### CODE REVIEW

**Comment by jacques-n** [comment]
@laurentgo I confirmed that the report did not appear until all the builds were done. I have no idea why it is saying coverage dropped. I think it may be because master is failing to run java.

**Comment by jacques-n** [comment]
Ping @laurentgo @rymurr

**Review by rymurr — APPROVED** [review]
LGTM. I am trusting codecov less and less . Getting pretty random results on my PRs today

**Comment by jacques-n** [comment]
I'm hoping this patch will make things more consistent.

**Comment by jacques-n** [comment]
@laurentgo do you have any concerns before I merge this?

**Review by laurentgo — APPROVED** [review]

**Pull request merged**
