### PR TITLE
Switch Nessie Docker images to use UID 10000

### PR DESCRIPTION
**Pull request by adutra**
Many companies have strict requirements on container security and a common convention is that containers should be run by non-root, non-system users with UID >= 1000.

### CODE REVIEW

**Comment by snazy** [comment]
Not really a fan of 1001 actually. I can see conflicts between the UID/GID of the container and the (same) UID/GID on the host. Why not randomly picked very high IDs?

**Comment by adutra** [comment]
Don't we already have the same problem with user 185?

I think UID 1001 is so commonly used in the k8s that I think it's safer to go with that than any other number.

**Comment by snazy** [comment]
`commonly used` is the culprit. 1001 would clash with those and existing UIDs/GIDs on the host ("normal users").

There is some [chatter](https://github.com/hexops-graveyard/dockerfile?tab=readme-ov-file#do-not-use-a-uid-below-10000) that one shouldn't use UID/GID below 10000 ([more](https://news.ycombinator.com/item?id=25621610)) to avoid some privilege escalation from a container.

**Comment by adutra** [comment]
I get the cons, but I think they only apply to users running the container in their laptops. No cloud provider in their right mind would ever grant any privilege to user 1001, because they would be basically granting privileges on their machines to half of the containers in the world :-)

But OK, let's change to 10000. Is that OK with you?

**Review by dimas-b — APPROVED** [review]
UID `10000` LGTM... However, I wonder if this is becoming more like a well-known port situation... If many containers use `10000` (good round number) for their UIDs, would it make sense for Nessie to use something like `29120` (related to the 19120 default port ;) )?

**Comment by adutra** [comment]
> UID `10000` LGTM... However, I wonder if this is becoming more like a well-known port situation... If many containers use `10000` (good round number) for their UIDs, would it make sense for Nessie to use something like `29120` (related to the 19120 default port ;) )?

I had the same idea, but not sure what's best honestly. It's also becoming a quest for the perfect UID which I think is a never-ending one... let's go with 10000, imho that's more than good enough!

**Comment by dimas-b** [comment]
>  let's go with 10000, imho that's more than good enough!

SGTM :+1:

**Pull request merged**
