### PR TITLE
set read timeout on client

### PR DESCRIPTION
**Pull request by rymurr**
This is to address the issue found in apache/iceberg#2328

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1016)

### CODE REVIEW

**Review by snazy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1016)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @rymurr)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6xvOkAmgEjtJ-YE6w:-MX6xvOkAmgEjtJ-YE6x:b-b3wdtu) (no related file):*
Being able to configure network timeouts is a good improvement!
Mind making the connect-timeout configurable as well?

---
___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 68 at r1](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6trseENHU0_NYTD5B:-MX6trseENHU0_NYTD5C:b-swn4mp) ([raw file](https://github.com/projectnessie/nessie/blob/2bb09d73468127d27f953996cbbd959eec039cfd/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L68)):*
> ```Java
>     private String password;
>     private boolean tracing;
>     private int readTimeout = 10;
> ```

I'd prefer milliseconds here, just because almost every HTTP client implementation uses milliseconds.
___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 68 at r1](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6xcGm6NLVW7wcAQA0:-MX6xcGm6NLVW7wcAQA1:b-dj1p3) ([raw file](https://github.com/projectnessie/nessie/blob/2bb09d73468127d27f953996cbbd959eec039cfd/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L68)):*
> ```Java
>     private String password;
>     private boolean tracing;
>     private int readTimeout = 10;
> ```

Just thinking: `sun.net.NetworkClient` uses the system property `sun.net.client.defaultReadTimeout` here, maybe we should use the same property as well, but just default to a > 0 default value. WDYT?
___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 177 at r1](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6u0RQCYSBxnnOALCZ:-MX6u0RRCXqns8bk01Pk:b2gfqa1) ([raw file](https://github.com/projectnessie/nessie/blob/2bb09d73468127d27f953996cbbd959eec039cfd/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L177)):*
> ```Java
>      * @return {@code this}
>      */
>     public Builder withReadTimeout(int readTimeout) {
> ```

Rename the param to `readTimeoutMillis`
___
*[clients/client/src/main/java/org/projectnessie/client/http/HttpClient.java, line 101 at r1](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6vNZ73X_MLtoB1x7v:-MX6vNZ73X_MLtoB1x7w:b-1l0cpz) ([raw file](https://github.com/projectnessie/nessie/blob/2bb09d73468127d27f953996cbbd959eec039cfd/clients/client/src/main/java/org/projectnessie/client/http/HttpClient.java#L101)):*
> ```Java
>     private ObjectMapper mapper;
>     private SSLContext sslContext;
>     private int readTimeout = 10;
> ```

I'd maybe give it a bit more by default - maybe 15 or 20 seconds.
___
*[clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java, line 70 at r1](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6wmk1B-c_oMyiACX2:-MX6wmk1B-c_oMyiACX3:bmcqqh) ([raw file](https://github.com/projectnessie/nessie/blob/2bb09d73468127d27f953996cbbd959eec039cfd/clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java#L70)):*
> ```Java
>   @Test
>   void testTimeout() {
>     HttpHandler handler = h -> {
> ```

Looks like this test runs for quite a long time. Guess, this probably needs some Mockito magic.

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1016)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @rymurr and @snazy)

___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 68 at r1](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6trseENHU0_NYTD5B:-MX7UhQ87lYpyT6XYtdT:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/2bb09d73468127d27f953996cbbd959eec039cfd/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L68)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

I'd prefer milliseconds here, just because almost every HTTP client implementation uses milliseconds.
</blockquote></details>

Done.
___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 68 at r1](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6xcGm6NLVW7wcAQA0:-MX7UhmWDICT-0FlzICd:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/2bb09d73468127d27f953996cbbd959eec039cfd/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L68)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Just thinking: `sun.net.NetworkClient` uses the system property `sun.net.client.defaultReadTimeout` here, maybe we should use the same property as well, but just default to a > 0 default value. WDYT?
</blockquote></details>

Done.
___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 177 at r1](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6u0RQCYSBxnnOALCZ:-MX7UiMa7aE9nqX60KaB:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/2bb09d73468127d27f953996cbbd959eec039cfd/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L177)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Rename the param to `readTimeoutMillis`
</blockquote></details>

Done.
___
*[clients/client/src/main/java/org/projectnessie/client/http/HttpClient.java, line 101 at r1](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6vNZ73X_MLtoB1x7v:-MX7Uj2AB2RRXhtAYRUx:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/2bb09d73468127d27f953996cbbd959eec039cfd/clients/client/src/main/java/org/projectnessie/client/http/HttpClient.java#L101)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

I'd maybe give it a bit more by default - maybe 15 or 20 seconds.
</blockquote></details>

Done.
___
*[clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java, line 70 at r1](https://reviewable.io/reviews/projectnessie/nessie/1016#-MX6wmk1B-c_oMyiACX2:-MX8KXo9CyXR4MTPsgmV:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/2bb09d73468127d27f953996cbbd959eec039cfd/clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java#L70)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Looks like this test runs for quite a long time. Guess, this probably needs some Mockito magic.
</blockquote></details>

Done.

**Review by snazy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1016)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @rymurr)

___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 70 at r2](https://reviewable.io/reviews/projectnessie/nessie/1016#-MXBMMWMC8bEvOFu-9SN:-MXBMMWMC8bEvOFu-9SO:bbjchjx) ([raw file](https://github.com/projectnessie/nessie/blob/ccb872bb016424117296ccc489fe6f252ebeacb3/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L70)):*
> ```Java
>     private boolean tracing;
>     private int readTimeoutMillis = Integer.parseInt(System.getProperty("sun.net.client.defaultReadTimeout", "25000"));
>     private int connectionTimeoutMillis = Integer.parseInt(System.getProperty("sun.net.client.defaultConnectionTimeout", "25000"));
> ```

That's maybe quite long for a TCP connect-timeout. 3 or 5 seconds is probably good enough.
___
*[clients/client/src/main/java/org/projectnessie/client/http/HttpRequest.java, line 149 at r2](https://reviewable.io/reviews/projectnessie/nessie/1016#-MXBM-u87ylSk8b7N9Fu:-MXBM-u87ylSk8b7N9Fv:b-ow0scx) ([raw file](https://github.com/projectnessie/nessie/blob/ccb872bb016424117296ccc489fe6f252ebeacb3/clients/client/src/main/java/org/projectnessie/client/http/HttpRequest.java#L149)):*
> ```Java
>     } catch (SocketTimeoutException e) {
>       throw new HttpClientReadTimeoutException(
>           String.format("Cannot finish request. Timeout while waiting for response with a timeout of %ds", readTimeoutMillis / 1000), e);
> ```

The exception message is wrong (both connect + read throw a SocketTimeoutExcepiton), maybe just mention both timeouts (in millis).
___
*[clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java, line 80 at r2](https://reviewable.io/reviews/projectnessie/nessie/1016#-MXBMpwFBaJiHJaBZEZa:-MXBMpwFBaJiHJaBZEZb:b-dycv2f) ([raw file](https://github.com/projectnessie/nessie/blob/ccb872bb016424117296ccc489fe6f252ebeacb3/clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java#L80)):*
> ```Java
>       try (TestServer server = new TestServer(handler)) {
>         get(server.getAddress(), 15000, 1).get().readEntity(ExampleBean.class);
>         Assertions.fail();
> ```

the Assertions.fail() is superfluous here ;)

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1016)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @rymurr and @snazy)

___
*[clients/client/src/main/java/org/projectnessie/client/NessieClient.java, line 70 at r2](https://reviewable.io/reviews/projectnessie/nessie/1016#-MXBMMWMC8bEvOFu-9SN:-MXBsL4pC-u5uqC72jOf:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/ccb872bb016424117296ccc489fe6f252ebeacb3/clients/client/src/main/java/org/projectnessie/client/NessieClient.java#L70)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

That's maybe quite long for a TCP connect-timeout. 3 or 5 seconds is probably good enough.
</blockquote></details>

Done.
___
*[clients/client/src/main/java/org/projectnessie/client/http/HttpRequest.java, line 149 at r2](https://reviewable.io/reviews/projectnessie/nessie/1016#-MXBM-u87ylSk8b7N9Fu:-MXBsQNt7eXPjWzpqhUy:b4n4xnb) ([raw file](https://github.com/projectnessie/nessie/blob/ccb872bb016424117296ccc489fe6f252ebeacb3/clients/client/src/main/java/org/projectnessie/client/http/HttpRequest.java#L149)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

The exception message is wrong (both connect + read throw a SocketTimeoutExcepiton), maybe just mention both timeouts (in millis).
</blockquote></details>

Where did you see that? I saw a different exception for connect. `ConnectException` or something.  
___
*[clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java, line 80 at r2](https://reviewable.io/reviews/projectnessie/nessie/1016#-MXBMpwFBaJiHJaBZEZa:-MXBshsfCYBmX1mT1rQc:bs7f4mp) ([raw file](https://github.com/projectnessie/nessie/blob/ccb872bb016424117296ccc489fe6f252ebeacb3/clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java#L80)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

the Assertions.fail() is superfluous here ;)
</blockquote></details>

yup, removed.

**Review by snazy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1016)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @rymurr)

___
*[clients/client/src/main/java/org/projectnessie/client/http/HttpRequest.java, line 149 at r2](https://reviewable.io/reviews/projectnessie/nessie/1016#-MXBM-u87ylSk8b7N9Fu:-MXBu3-yEULH0RkWyzWl:b-g6akk9) ([raw file](https://github.com/projectnessie/nessie/blob/ccb872bb016424117296ccc489fe6f252ebeacb3/clients/client/src/main/java/org/projectnessie/client/http/HttpRequest.java#L149)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Where did you see that? I saw a different exception for connect. `ConnectException` or something.  
</blockquote></details>

In the javadoc for `java.net.Socket#connect(java.net.SocketAddress, int)`. But since you mention it, IIRC it's really `ConnectException` - interesting, that it's different from the javadoc.

**Pull request merged**
