### PR TITLE
Extract TieredVersionStore into separate module 

### PR DESCRIPTION
**Pull request by jacques-n**
Also Introduce basic Store-level exceptions

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/550)

### CODE REVIEW

**Review by rymurr — APPROVED** [review]
LGTM.

I would love to introduce a new abstraction for the expression stuff. I think it mixes two things:

1) a solid abstraction over dynamo (that imho could be published on its own)
2) an interface to query an underlying Store. This could be separated from the dynamo stuff and made simpler/easier to implement

Not something we need to do now of course. But I think it would be worthwhile.

**Review by rymurr — DISMISSED** [review]
> Reviewed 59 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/550)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @laurentgo)

**Review by laurentgo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/550)* status: all files reviewed, 8 unresolved discussions (waiting on @jacques-n)

___
*[versioned/pom.xml, line 34 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOX8GqH43AzkhEx5lpo:-MOX8GqH43AzkhEx5lpp:b-t0estd) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/pom.xml#L34)):*
> ```XML
> 
>   <modules>
>     <module>tiered</module>
> ```

(style) the list is sorted alphabetically?
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 153 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOX8W0g7H7XPbCHLrPv:-MOX8W0g7H7XPbCHLrPw:blvouko) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L153)):*
> ```Java
> 
>     } catch (RuntimeException ex) {
>       throw new StoreOperationException("Failure connection to Dynamo", ex);
> ```

tbh, I don't see the value of wrapping any `RuntimeException` into a subclass of `RuntimeException` (vs targeting some specific exceptions) because there's a chance that some exception might not be caused by the store, but that the upper level would just catch storeexception and ignore it for example (retry policy or something else)
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 192 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOX9AsxBD1RXeQ8lk0e:-MOX9AsxBD1RXeQ8lk0f:b8n33ws) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L192)):*
> ```Java
>             }
> 
>             throw new NotFoundException(
> ```

not caused by that changed, but the exception is not that informative, or too informative. In particular, instead of the count, it would be interesting to get an example of missing objects.
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 320 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOX9ZRG9xRJOlbuCGSz:-MOX9ZRG9xRJOlbuCGT-:b-ppgpl9) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L320)):*
> ```Java
>       throw new RuntimeException(e);
>     } catch (ExecutionException e) {
>       throw new StoreOperationException("Failure during save", e.getCause());
> ```

same comment regarding `RuntimeException` being wrapped up...
___
*[versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/ConditionFailedException.java, line 21 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOX9vhe0W172k4b_XLM:-MOX9vhe0W172k4b_XLN:b-6ozi0p) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/ConditionFailedException.java#L21)):*
> ```Java
>  * Thrown when a conditional operation fails.
>  */
> public class ConditionFailedException extends StoreException {
> ```

As exceptions are serializable, and even we are not using serialization, maybe add a serial version, or a `@SuppressWarning` annotation?
___
*[versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/NotFoundException.java, line 21 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOXA9wuDpe-cEVrq3rd:-MOXA9wuDpe-cEVrq3re:b-6ozi0p) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/NotFoundException.java#L21)):*
> ```Java
>  * Thrown when an expected object does not exist.
>  */
> public class NotFoundException extends StoreException {
> ```

As exceptions are serializable, and even we are not using serialization, maybe add a serial version, or a `@SuppressWarning` annotation?
___
*[versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/StoreException.java, line 18 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOXAFmF3eE0LgHogPK1:-MOXAFmF3eE0LgHogPK2:b-uytgi1) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/StoreException.java#L18)):*
> ```Java
> package com.dremio.nessie.versioned.store;
> 
> public class StoreException extends RuntimeException {
> ```

As exceptions are serializable, and even we are not using serialization, maybe add a serial version, or a `@SuppressWarning` annotation?

Also, not sure about the choice of making it unchecked, I would have likely used `IOException` instead, or `Exception` if those exceptions are expected to be acted upon (which seems to be the case here)
___
*[versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/StoreOperationException.java, line 21 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOXB2W59ak-X5QiZRJN:-MOXB2W59ak-X5QiZRJO:b-6ozi0p) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/StoreOperationException.java#L21)):*
> ```Java
>  * Thrown when a store operation fails unexpectedly.
>  */
> public class StoreOperationException extends StoreException {
> ```

As exceptions are serializable, and even we are not using serialization, maybe add a serial version, or a `@SuppressWarning` annotation?
___
*[versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/Store.java, line 30 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOXAX4kDkxzlB4VJmh4:-MOXAX4kDkxzlB4VJmh5:bjvmolk) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/Store.java#L30)):*
> ```Java
>   String KEY_NAME = "id";
> 
>   void start() throws StoreOperationException;
> ```

there's little point of adding it to the interface because unchecked. Note how the implementations do not redeclare the exception on their signature, and there's no error.
There's more value mentioning in the javadoc and explaining when the exception is thrown though...

**Review by jacques-n — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/550)* status: 51 of 59 files reviewed, 8 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[versioned/pom.xml, line 34 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOX8GqH43AzkhEx5lpo:-MOYNWwP1QEBKs2uPSJl:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/pom.xml#L34)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

(style) the list is sorted alphabetically?
</blockquote></details>

Done.
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 153 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOX8W0g7H7XPbCHLrPv:-MOYNb9B4PP5cT5diKIA:byacjxz) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L153)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

tbh, I don't see the value of wrapping any `RuntimeException` into a subclass of `RuntimeException` (vs targeting some specific exceptions) because there's a chance that some exception might not be caused by the store, but that the upper level would just catch storeexception and ignore it for example (retry policy or something else)
</blockquote></details>

Yeah, that should have been DynamoDbException. Fixed.
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 192 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOX9AsxBD1RXeQ8lk0e:-MOYNgx-4NpLlM1DeABk:b-67jomq) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L192)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

not caused by that changed, but the exception is not that informative, or too informative. In particular, instead of the count, it would be interesting to get an example of missing objects.
</blockquote></details>

It does list the missing objects...
___
*[versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 320 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOX9ZRG9xRJOlbuCGSz:-MOYOq7l7BcWYrXH95Gb:b-pcprqi) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L320)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

same comment regarding `RuntimeException` being wrapped up...
</blockquote></details>

cleaned up.
___
*[versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/ConditionFailedException.java, line 21 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOX9vhe0W172k4b_XLM:-MOYOrYz219LoRUaHI_u:bb7f2mf) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/ConditionFailedException.java#L21)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

As exceptions are serializable, and even we are not using serialization, maybe add a serial version, or a `@SuppressWarning` annotation?
</blockquote></details>

done
___
*[versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/NotFoundException.java, line 21 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOXA9wuDpe-cEVrq3rd:-MOYOs7O5bZBbmYi2Iq6:bb7f2mf) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/NotFoundException.java#L21)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

As exceptions are serializable, and even we are not using serialization, maybe add a serial version, or a `@SuppressWarning` annotation?
</blockquote></details>

done
___
*[versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/StoreException.java, line 18 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOXAFmF3eE0LgHogPK1:-MOYOxLBDZB6Rss64kwr:b-v6hq7h) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/StoreException.java#L18)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

As exceptions are serializable, and even we are not using serialization, maybe add a serial version, or a `@SuppressWarning` annotation?

Also, not sure about the choice of making it unchecked, I would have likely used `IOException` instead, or `Exception` if those exceptions are expected to be acted upon (which seems to be the case here)
</blockquote></details>

Added suppress. Also, given the use of streams, etc, I kept unchecked.
___
*[versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/StoreOperationException.java, line 21 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOXB2W59ak-X5QiZRJN:-MOYP1v15QBI7J90IrE9:bb7f2mf) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/StoreOperationException.java#L21)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

As exceptions are serializable, and even we are not using serialization, maybe add a serial version, or a `@SuppressWarning` annotation?
</blockquote></details>

done
___
*[versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/Store.java, line 30 at r1](https://reviewable.io/reviews/projectnessie/nessie/550#-MOXAX4kDkxzlB4VJmh4:-MOYOupZDoeT9kQnJPci:b-xa92sw) ([raw file](https://github.com/projectnessie/nessie/blob/81cacd22a5f061d12bbfb30707f29294a987c7fe/versioned/tiered/src/main/java/com/dremio/nessie/versioned/store/Store.java#L30)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

there's little point of adding it to the interface because unchecked. Note how the implementations do not redeclare the exception on their signature, and there's no error.
There's more value mentioning in the javadoc and explaining when the exception is thrown though...
</blockquote></details>

updated. now doc'd, not declared.

**Review by laurentgo — APPROVED** [review]

**Pull request merged**
