### PR TITLE
Fix handling of tag/branch names in the REST API paths containging ch…

### LINKED ISSUE #395: Ensure rest apis handle branches & tags with slashes in them

### PR DESCRIPTION
**Pull request by snazy**
…aracters that need to be escaped.

Characters like `%`, `/`, etc need to be URI-escaped in the HTTP request URI to work properly.

The fix is rather simple: just use `javax.ws.rs.client.WebTarget#resolveTemplate(java.lang.String, java.lang.Object, boolean)` where necessary.

We probably also need some functionality to check whether a tag/branch names contains valid characters to prevent that "bad" characters (e.g. control characters) get into the systems.

Fixes #395

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/576)

### CODE REVIEW

**Review by laurentgo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/576)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jacques-n, @laurentgo, and @snazy)

___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java, line 97 at r1](https://reviewable.io/reviews/projectnessie/nessie/576#-MOgL11X5q8m0rKl1PXn:-MOgL11X5q8m0rKl1PXo:b-9o1cig) ([raw file](https://github.com/projectnessie/nessie/blob/1ed9a65f61449b10f01a4e7053ff9714b217399c/servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java#L97)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>       List<Reference> references = tree.getAllReferences();
>       Reference tagRef = references.stream().filter(r -> tagName.equals(r.getName())).findFirst().orElse(null);
>       Reference branchRef = references.stream().filter(r -> branchName.equals(r.getName())).findFirst().orElse(null);
>       Reference branchRef2 = references.stream().filter(r -> branchName2.equals(r.getName())).findFirst().orElse(null);
> ```
</details>

Maybe we should collect into a collection and use custom matcher? + containsInAnyOrder matcher to verify the collection.
___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java, line 138 at r1](https://reviewable.io/reviews/projectnessie/nessie/576#-MOgLQHr0gCGhRjTqqQX:-MOgLQHr0gCGhRjTqqQY:b-y3egco) ([raw file](https://github.com/projectnessie/nessie/blob/1ed9a65f61449b10f01a4e7053ff9714b217399c/servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java#L138)):*
> ```Java
>       tree.deleteBranch(branchName, newHash);
>     } finally {
>       try {
> ```

I wonder if we can have the store reset between store instead of doing manual cleanup

**Review by laurentgo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/576)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @jacques-n and @snazy)

___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/ReferenceMatchers.java, line 27 at r2](https://reviewable.io/reviews/projectnessie/nessie/576#-MOhT_0REElsg5zzqpgw:-MOhT_0REElsg5zzqpgx:bt10kwk) ([raw file](https://github.com/projectnessie/nessie/blob/16ac6ee2cf6624a0e20e8c357e382ca5ba5a8c59/servers/quarkus-server/src/test/java/com/dremio/nessie/server/ReferenceMatchers.java#L27)):*
> ```Java
> import com.dremio.nessie.model.Reference;
> 
> public class ReferenceMatchers {
> ```

to be `final` with a private constructor I guess since it's a utility class?
___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/ReferenceMatchers.java, line 28 at r2](https://reviewable.io/reviews/projectnessie/nessie/576#-MOhTff7DB-RYgi0k48O:-MOhTff82_4PdY7MA3hZ:bh94oid) ([raw file](https://github.com/projectnessie/nessie/blob/16ac6ee2cf6624a0e20e8c357e382ca5ba5a8c59/servers/quarkus-server/src/test/java/com/dremio/nessie/server/ReferenceMatchers.java#L28)):*
> ```Java
> 
> public class ReferenceMatchers {
>   public static Matcher<Reference> referenceWithName(@Nonnull String refName) {
> ```

javadoc please? (I'm surprised checkstyle didn't complain tbh)
___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java, line 97 at r1](https://reviewable.io/reviews/projectnessie/nessie/576#-MOgL11X5q8m0rKl1PXn:-MOhUAhZEh5zdho2wLlc:b-832hn8) ([raw file](https://github.com/projectnessie/nessie/blob/1ed9a65f61449b10f01a4e7053ff9714b217399c/servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java#L97)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

> ```
>       List<Reference> references = tree.getAllReferences();
>       Reference tagRef = references.stream().filter(r -> tagName.equals(r.getName())).findFirst().orElse(null);
>       Reference branchRef = references.stream().filter(r -> branchName.equals(r.getName())).findFirst().orElse(null);
>       Reference branchRef2 = references.stream().filter(r -> branchName2.equals(r.getName())).findFirst().orElse(null);
> ```
Maybe we should collect into a collection and use custom matcher? + containsInAnyOrder matcher to verify the collection.
</blockquote></details>

Did you forget to use your matchers? :)

**Comment by snazy** [comment]
> 
> Previously, laurentgo (Laurent Goujon) wrote…
> Did you forget to use your matchers? :)

Hm - nope ;)

No clue why codecov complains though.

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/576)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @jacques-n and @snazy)

___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java, line 94 at r3](https://reviewable.io/reviews/projectnessie/nessie/576#-MOk4fZyDwMzMM_8Lajg:-MOk4fZz5UcwMmvfUkFm:b-92wc58) ([raw file](https://github.com/projectnessie/nessie/blob/6d7b888b04225b4b291aedb4d0d52df9764c1fad/servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java#L94)):*
> ```Java
>       "with%sign",
>       "slash/thing",
>       "all the/things%:*\u00E4\u00F6\u00FC" // some german umlauts as well
> ```

Do we want to support some of the characters here. as per #578 the umlaut characters and perhaps the % are going to be disallowed in the ref name. Happy to address this in a separate patch though.

**Review by snazy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/576)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @jacques-n, @rymurr, and @snazy)

___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java, line 94 at r3](https://reviewable.io/reviews/projectnessie/nessie/576#-MOk4fZyDwMzMM_8Lajg:-MOkxt8n7Ms3GHhB_moq:b-73m6vw) ([raw file](https://github.com/projectnessie/nessie/blob/6d7b888b04225b4b291aedb4d0d52df9764c1fad/servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java#L94)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Do we want to support some of the characters here. as per #578 the umlaut characters and perhaps the % are going to be disallowed in the ref name. Happy to address this in a separate patch though.
</blockquote></details>

Nice catch!

**Review by rymurr — DISMISSED** [review]
LGTM, I am happy if @laurentgo is

**Review by laurentgo — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/576)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @jacques-n, @rymurr, and @snazy)

___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java, line 85 at r4](https://reviewable.io/reviews/projectnessie/nessie/576#-MOlinZf30DhVxoaaPRh:-MOlinZf30DhVxoaaPRi:b-bkfpmy) ([raw file](https://github.com/projectnessie/nessie/blob/7ba219554a51efb5f456843c656e26b8608f989f/servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java#L85)):*
> ```Java
> 
>     assertThat(versionStore, instanceOf(InMemoryVersionStore.class));
>     ((InMemoryVersionStore<?, ?>)versionStore).clearUnsafe();
> ```

I guess it depends on what store is used for tests, and this is conditioned by application.properties?
___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java, line 105 at r4](https://reviewable.io/reviews/projectnessie/nessie/576#-MOliTgo6H6oHJVozMFa:-MOliTgo6H6oHJVozMFb:bm2ibee) ([raw file](https://github.com/projectnessie/nessie/blob/7ba219554a51efb5f456843c656e26b8608f989f/servers/quarkus-server/src/test/java/com/dremio/nessie/server/TestRest.java#L105)):*
> ```
> r -> r
> ```
One can use `Function.identity()`
___
*[versioned/memory/src/main/java/com/dremio/nessie/versioned/memory/InMemoryVersionStore.java, line 513 at r4](https://reviewable.io/reviews/projectnessie/nessie/576#-MOliyvM1w7JBap62x4Z:-MOliyvN6q8WTSPBBbOl:b-4rva03) ([raw file](https://github.com/projectnessie/nessie/blob/7ba219554a51efb5f456843c656e26b8608f989f/versioned/memory/src/main/java/com/dremio/nessie/versioned/memory/InMemoryVersionStore.java#L513)):*
> ```Java
>    */
>   @VisibleForTesting
>   public void clearUnsafe() throws ReferenceNotFoundException, ReferenceAlreadyExistsException {
> ```

seems a bit weird tbh to throws those exception if store is being reset...

**Review by laurentgo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/576)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @jacques-n, @rymurr, and @snazy)

**Comment by snazy** [comment]
Thanks for the reviews !

**Pull request merged**
