### PR TITLE
Update camelcase to v7.x

### PR DESCRIPTION
**Pull request by VladimirYushkevich**
This branch is based on https://github.com/projectnessie/nessie/pull/5305.

In this PR:
* Fixed import for new version of `camelcase` by moving it from top level into method body. This allows to suppress ERR_REQUIRE_ESM error.

### CODE REVIEW

**Review by ajantha-bhat — APPROVED** [review]

**Review by XN137 — COMMENTED** [review]
the release notes of v7 have:

> This package is now pure ESM. Please [read this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

wondering: have we tried the suggested approach already?

i am no JS/node expert but i am guessing the suggested "fix" might not actually work, we just happen to not process `.svg` files as part of our build, so the import doesnt get executed now.

**Comment by VladimirYushkevich** [comment]
> wondering: have we tried the suggested approach already?
I tried this: 
```
import { camelCase } from "camelcase";

 import { camelCase } from "camelcase";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```
> i am no JS/node expert but i am guessing the suggested "fix" might not actually work, we just happen to not process `.svg` files as part of our build, so the import doesnt get executed now.

Exactly. Looks like the code in `fileTransform.js` is not executed now.

**Comment by XN137** [comment]
just to be clear:
with "the suggested fix doesnt work" i was talking about this PR, not the changes suggested in the gist.

imo it doesnt make sense to upgrade this library and fix new problems by avoiding its usage...

unless we find an easy way to fix the import "correctly" or we are planning to migrate the project to [ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-move-my-commonjs-project-to-esm) completely (which might not be a good use of our time right now), we should imo just not bother upgrading the library for now...
after all its just for camel casing a string?

**Comment by XN137** [comment]
i think closing the original PR will mark it as ignored/blocked in the dependency dashboard:
https://github.com/projectnessie/nessie/issues/5255
and we would need to click a checkbox to reactivate it

**Comment by snazy** [comment]
I'm okay with closing (and not yet bothering about the dependency update).

**Pull request closed without merging**
