### PR TITLE
[BUG-9620] Adding metadata.namespace to all helm template files

### PR DESCRIPTION
**Pull request by ev1lm0nk3y**
This should resolve https://github.com/projectnessie/nessie/issues/9620

### CODE REVIEW

**Comment by adutra** [comment]
@ev1lm0nk3y Our CLA assistant is not able to recognize your commit. Can you change that and sign the CLA please? 🙏

**Comment by adutra** [comment]
@ev1lm0nk3y heads up: due to conflicts, you need to rebase and fix things in `service.yaml`, `management-service.yaml` (deleted) and `service-monitor.yaml`.

**Comment by ev1lm0nk3y** [comment]
Sure, I can do that. Gimme a few days

**Comment by adutra** [comment]
@ev1lm0nk3y any progress on this? Otherwise I could go ahead and tackle this myself.

**Comment by adutra** [comment]
Closing in favor of #9711.

**Pull request closed without merging**
