### PR TITLE
add a uuid to all contents types

### PR DESCRIPTION
**Pull request by rymurr**
the UUID is unique to the object for its lifetime regardless of its key.

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1023)

### CODE REVIEW

**Comment by rymurr** [comment]
This is really interesting. The iceberg garbage collection algorithm has `0.4.0` of `NessieClient` from iceberg `0.11.0` which is incompatible with this change. Really hard to work this one out...

**Review by laurentgo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1023)* status: 0 of 24 files reviewed, 2 unresolved discussions (waiting on @rymurr and @snazy)

___
*[model/src/main/java/org/projectnessie/model/Contents.java, line 72 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXjXRkK3-QpatGY43Zm:-MXjXRkK3-QpatGY43Zn:blctjzc) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/model/src/main/java/org/projectnessie/model/Contents.java#L72)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>   /**
>    * Unique uuid for this object.
>    *
>    * <p>This uuid is unique for the entire lifetime of this Contents object and persist across renames. Two contents with the same key
>    * will have different uuids.
>    *
>    * <p>todo this is nullable to maintain backwards compatibility with the version of nessie deployed with iceberg. Remove after 0.6.0 is
>    *     finished
>    */
>   @Nullable
>   public abstract String getUuid();
> ```
</details>

Should it simply be called id? 
and if a true UUID, should UUID class be used instead? (So that it might be easier to enforce the format and allow for storage optimization)?
___
*[servers/store/src/main/proto/table.proto, line 35 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXjYop00QoVA651SAmz:-MXjYop00QoVA651SAn-:b-ryffe0) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/servers/store/src/main/proto/table.proto#L35)):*
> ```protobuf
> message IcebergTable {
>   string metadata_location = 1;
>   string uuid = 2;
> ```

maybe a uuid type would be nice to have a more compact representation? 
Also, shouldn't the field be a member of Contents instead if it is common to all types?

**Review by snazy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1023)* status: 0 of 24 files reviewed, 8 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[model/src/main/java/org/projectnessie/model/Contents.java, line 65 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkiFQKEy337nJX-set:-MXkiFQKEy337nJX-seu:b1mh4mk) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/model/src/main/java/org/projectnessie/model/Contents.java#L65)):*
> ```Java
>    * Unique uuid for this object.
>    *
>    * <p>This uuid is unique for the entire lifetime of this Contents object and persist across renames. Two contents with the same key
> ```

Nit: typo ("and persist across renames")
___
*[model/src/main/java/org/projectnessie/model/Contents.java, line 68 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkiOTyBRnb2uqrdF5T:-MXkiOTyBRnb2uqrdF5U:bmhw1l5) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/model/src/main/java/org/projectnessie/model/Contents.java#L68)):*
> ```Java
>    * will have different uuids.
>    *
>    * <p>todo this is nullable to maintain backwards compatibility with the version of nessie deployed with iceberg. Remove after 0.6.0 is
> ```

Requires a follow-up issue or a prepared PR.
___
*[model/src/main/java/org/projectnessie/model/Contents.java, line 72 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXjXRkK3-QpatGY43Zm:-MXkiZDq6ajbRaBgEp91:b32v57) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/model/src/main/java/org/projectnessie/model/Contents.java#L72)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

> ```
>   /**
>    * Unique uuid for this object.
>    *
>    * <p>This uuid is unique for the entire lifetime of this Contents object and persist across renames. Two contents with the same key
>    * will have different uuids.
>    *
>    * <p>todo this is nullable to maintain backwards compatibility with the version of nessie deployed with iceberg. Remove after 0.6.0 is
>    *     finished
>    */
>   @Nullable
>   public abstract String getUuid();
> ```
Should it simply be called id? 
and if a true UUID, should UUID class be used instead? (So that it might be easier to enforce the format and allow for storage optimization)?
</blockquote></details>

+1
___
*[model/src/main/java/org/projectnessie/model/Contents.java, line 72 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkjGxd1FpiE5eJvPi3:-MXkjGxd1FpiE5eJvPi4:b-kkef7z) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/model/src/main/java/org/projectnessie/model/Contents.java#L72)):*
> ```Java
>    */
>   @Nullable
>   public abstract String getUuid();
> ```

Think this needs some validation that you cannot accidentally override an existing value. E.g. a `ImmutableIcebergTable.from(table).withUuld(...)` should bark.
___
*[python/tests/cassettes/test_nessie_cli/test_assign.yaml, line 16 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkgcwF71d2NvLJZIKN:-MXkgcwF71d2NvLJZIKO:b-tkzcu1) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/python/tests/cassettes/test_nessie_cli/test_assign.yaml#L16)):*
> ```YAML
>       - application/json
>       User-Agent:
>       - python-requests/2.24.0
> ```

Huh? Older library?
___
*[servers/quarkus-server/src/test/java/org/projectnessie/server/RestGitTest.java, line 83 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkilo115ADC4zeOMz7:-MXkilo115ADC4zeOMz8:b-zg0w5l) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/servers/quarkus-server/src/test/java/org/projectnessie/server/RestGitTest.java#L83)):*
> ```Java
>            .statusCode(200).extract().as(Branch.class));
> 
>     IcebergTable table = ImmutableIcebergTable.builder().uuid(UUID.randomUUID().toString())
> ```

Can use `IcebergTable.of()`
___
*[servers/store/src/main/java/org/projectnessie/server/store/TableCommitMetaStoreWorker.java, line 47 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkkewX4TPFvkYiNcDt:-MXkkewX4TPFvkYiNcDu:b9um16i) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/servers/store/src/main/java/org/projectnessie/server/store/TableCommitMetaStoreWorker.java#L47)):*
> ```Java
> import com.google.protobuf.UnsafeByteOperations;
> 
> public class TableCommitMetaStoreWorker implements StoreWorker<Contents, CommitMeta, Contents.Type> {
> ```

I think, this class requires some unit tests, that validates both serialization + deserialization.

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1023)* status: 0 of 24 files reviewed, 7 unresolved discussions (waiting on @laurentgo and @snazy)

___
*[model/src/main/java/org/projectnessie/model/Contents.java, line 68 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkiOTyBRnb2uqrdF5T:-MXklP0u5X8enh10n7i9:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/model/src/main/java/org/projectnessie/model/Contents.java#L68)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Requires a follow-up issue or a prepared PR.
</blockquote></details>

Done.
___
*[model/src/main/java/org/projectnessie/model/Contents.java, line 72 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXjXRkK3-QpatGY43Zm:-MXklU98093t_OWg-Sy4:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/model/src/main/java/org/projectnessie/model/Contents.java#L72)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[model/src/main/java/org/projectnessie/model/Contents.java, line 72 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkjGxd1FpiE5eJvPi3:-MXkoQC65Ddu-rsxO0uD:b-gii7ve) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/model/src/main/java/org/projectnessie/model/Contents.java#L72)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Think this needs some validation that you cannot accidentally override an existing value. E.g. a `ImmutableIcebergTable.from(table).withUuld(...)` should bark.
</blockquote></details>

This is really hard by the looks of it. I am just scanning through https://immutables.github.io/immutable.html#precondition-check-method and don't see any easy way to do this. Thoughts?

Perhaps we make Contents an immutables value and use a strict builder? Possible we would have to really fiddle though.
___
*[python/tests/cassettes/test_nessie_cli/test_assign.yaml, line 16 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkgcwF71d2NvLJZIKN:-MXkodMt4j7KOPxEy-Bu:b-qay3bf) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/python/tests/cassettes/test_nessie_cli/test_assign.yaml#L16)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Huh? Older library?
</blockquote></details>

https://github.com/projectnessie/nessie/blob/main/python/requirements.txt#L9 this file was generated w/ a slightly older version of the `requests` lib. The `requests` lib interface is stable so this shouldn't matter. (Note 2.24.0 is NOT the python version)
___
*[servers/quarkus-server/src/test/java/org/projectnessie/server/RestGitTest.java, line 83 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkilo115ADC4zeOMz7:-MXkp3jGEc6z-P4ApGei:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/servers/quarkus-server/src/test/java/org/projectnessie/server/RestGitTest.java#L83)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Can use `IcebergTable.of()`
</blockquote></details>

Done.
___
*[servers/store/src/main/java/org/projectnessie/server/store/TableCommitMetaStoreWorker.java, line 47 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkkewX4TPFvkYiNcDt:-MXkpBVk9pge_8tBxK_d:bpcas3h) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/servers/store/src/main/java/org/projectnessie/server/store/TableCommitMetaStoreWorker.java#L47)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

I think, this class requires some unit tests, that validates both serialization + deserialization.
</blockquote></details>

Sure, can do. Anything specific you are looking for here? I am happy to add a full serde unit test but would rather do that as a separate PR
___
*[servers/store/src/main/proto/table.proto, line 35 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXjYop00QoVA651SAmz:-MXkpJn6Dh8n3YnTm1Oq:b-rww7hs) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/servers/store/src/main/proto/table.proto#L35)):*
> Also, shouldn't the field be a member of Contents instead if it is common to all types?
Done.

> maybe a uuid type would be nice to have a more compact representation?
How do you mean?

**Review by snazy — COMMENTED** [review]
Having convenience methods like `withMetadataLocation()` is fine.
Not sure whether we really need to be that restrictive with the visibility change and extending the `Builder` classes.
I think, just having the `@Value.Default` on `getId()` is good enough. Maybe having static methods to instantiate a builder for a new content object is even clearer for people to use.

**Comment by rymurr** [comment]
> Having convenience methods like `withMetadataLocation()` is fine.
> Not sure whether we really need to be that restrictive with the visibility change and extending the `Builder` classes.
Yeah, its restrictive and I thikn the builder extension is redundant. I think its the most direct way to avoid accidental modification of `id`. Its ok for contents with few methods but is ugly for larger objects.

> I think, just having the `@Value.Default` on `getId()` is good enough. Maybe having static methods to instantiate a builder for a new content object is even clearer for people to use.
Just adding `Default` doesn't really do anything, it is still settable by the builder and changeable with `from`. Its a nice convenience but it doesn't address the original problem of people changing `id`.

From this can I surmise that preventing accidental changes of `id` isn't worth the extra boilerplate? I will revert the last commit then (aside from the `Default` annotation)?

**Comment by snazy** [comment]
> > Having convenience methods like `withMetadataLocation()` is fine.
> > Not sure whether we really need to be that restrictive with the visibility change and extending the `Builder` classes.
> > Yeah, its restrictive and I thikn the builder extension is redundant. I think its the most direct way to avoid accidental modification of `id`. Its ok for contents with few methods but is ugly for larger objects.
> 
> > I think, just having the `@Value.Default` on `getId()` is good enough. Maybe having static methods to instantiate a builder for a new content object is even clearer for people to use.
> > Just adding `Default` doesn't really do anything, it is still settable by the builder and changeable with `from`. Its a nice convenience but it doesn't address the original problem of people changing `id`.
> 
> From this can I surmise that preventing accidental changes of `id` isn't worth the extra boilerplate? I will revert the last commit then (aside from the `Default` annotation)?

Just having the `@Value.Default` is probably worth it.

**Comment by rymurr** [comment]
ok, reverted the fancy builders change and added `Default` annotation

**Comment by snazy** [comment]
> ok, reverted the fancy builders change and added `Default` annotation

Yea, that looks good now.

**Review by snazy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1023)* status: 0 of 24 files reviewed, 13 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

___
*[clients/deltalake/core/src/main/scala/org/projectnessie/deltalake/NessieLogStore.scala, line 107 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmHd9l5cr-_JrrCoKP:-MXmHd9l5cr-_JrrCoKQ:b-uhu5tl) ([raw file](https://github.com/projectnessie/nessie/blob/a6d4eab1ddba3b10099b5f65885940c64f40e828/clients/deltalake/core/src/main/scala/org/projectnessie/deltalake/NessieLogStore.scala#L107)):*
> ```Scala
>   private def updateDeltaTable(path: Path, targetRef: String, lastCheckpoint: String = null): DeltaLakeTable = {
>     val currentTable = getTable(path.getParent, targetRef)
>     val table = currentTable.map(ImmutableDeltaLakeTable.copyOf).getOrElse(ImmutableDeltaLakeTable.builder().build())
> ```

Mind reverting this change in this PR? It's a noop
___
*[clients/hmsbridge/core/src/main/java/org/projectnessie/hms/Item.java, line 41 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmHH8B4AJZ-c_NMILB:-MXmHH8B4AJZ-c_NMILC:bhevg34) ([raw file](https://github.com/projectnessie/nessie/blob/dcb0c486c2a6fcbb48dfda297610d3875b950114/clients/hmsbridge/core/src/main/java/org/projectnessie/hms/Item.java#L41)):*
> ```Java
>   public abstract Contents toContents();
> 
>   public abstract String getUuid();
> ```

Think should be `getId()` (and elsewhere in all the hms classes)
___
*[model/src/main/java/org/projectnessie/model/IcebergTable.java, line 35 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmGzGY6lWmeQIDpNWs:-MXmGzGY6lWmeQIDpNWt:b-fbho65) ([raw file](https://github.com/projectnessie/nessie/blob/dcb0c486c2a6fcbb48dfda297610d3875b950114/model/src/main/java/org/projectnessie/model/IcebergTable.java#L35)):*
> ```Java
> 
>   public static IcebergTable of(String metadataLocation) {
>     return ImmutableIcebergTable.builder().metadataLocation(metadataLocation).id(UUID.randomUUID().toString()).build();
> ```

Think this change can go away now ;)
___
*[python/pynessie/model.py, line 17 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmHQm077JY-BytKSYu:-MXmHQm077JY-BytKSYv:b58ajue) ([raw file](https://github.com/projectnessie/nessie/blob/dcb0c486c2a6fcbb48dfda297610d3875b950114/python/pynessie/model.py#L17)):*
> ```Python
>     """Dataclass for Nessie Contents."""
> 
>     uuid: str = desert.ib(fields.Str())
> ```

Think this should just be `id` (+ tests updated)
___
*[versioned/gc/iceberg/pom.xml, line 34 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmHo_MBKRDc3V7FlLT:-MXmHo_MBKRDc3V7FlLU:b-gpurpa) ([raw file](https://github.com/projectnessie/nessie/blob/dcb0c486c2a6fcbb48dfda297610d3875b950114/versioned/gc/iceberg/pom.xml#L34)):*
> ```XML
> 
>   <properties>
>     <iceberg.nessie.version>0.4.0</iceberg.nessie.version>
> ```

Can you pull this into a separate PR?
The change is fine, just unrelated to the intent of this PR

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1023)* status: 0 of 22 files reviewed, 13 unresolved discussions (waiting on @laurentgo and @snazy)

___
*[clients/deltalake/core/src/main/scala/org/projectnessie/deltalake/NessieLogStore.scala, line 107 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmHd9l5cr-_JrrCoKP:-MXrAohq85CwEoXw9LmP:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/a6d4eab1ddba3b10099b5f65885940c64f40e828/clients/deltalake/core/src/main/scala/org/projectnessie/deltalake/NessieLogStore.scala#L107)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Mind reverting this change in this PR? It's a noop
</blockquote></details>

Done.
___
*[clients/hmsbridge/core/src/main/java/org/projectnessie/hms/Item.java, line 41 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmHH8B4AJZ-c_NMILB:-MXrBT1-2SAbY__7lW6y:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/dcb0c486c2a6fcbb48dfda297610d3875b950114/clients/hmsbridge/core/src/main/java/org/projectnessie/hms/Item.java#L41)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Think should be `getId()` (and elsewhere in all the hms classes)
</blockquote></details>

Done.
___
*[model/src/main/java/org/projectnessie/model/IcebergTable.java, line 39 at r2](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXIXLaav_DYKHZjmbB_-r2-39:-MXrB_g5EFPcKd7Qt-Px:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/0120d6de149c01de812a6404012c28c6461f08f2/model/src/main/java/org/projectnessie/model/IcebergTable.java#L39)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Maybe rename to `withMetadataLocation`
</blockquote></details>

Done.
___
*[model/src/main/java/org/projectnessie/model/IcebergTable.java, line 35 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmGzGY6lWmeQIDpNWs:-MXrB_3DBjHi_4eFdUEc:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/dcb0c486c2a6fcbb48dfda297610d3875b950114/model/src/main/java/org/projectnessie/model/IcebergTable.java#L35)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Think this change can go away now ;)
</blockquote></details>

Done.
___
*[python/pynessie/model.py, line 17 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmHQm077JY-BytKSYu:-MXrDApG5VxLnfkfGF1d:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/dcb0c486c2a6fcbb48dfda297610d3875b950114/python/pynessie/model.py#L17)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Think this should just be `id` (+ tests updated)
</blockquote></details>

Done.
___
*[versioned/gc/iceberg/pom.xml, line 34 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmHo_MBKRDc3V7FlLT:-MXrDCi75AfJds0z92GR:b-nkb4dp) ([raw file](https://github.com/projectnessie/nessie/blob/dcb0c486c2a6fcbb48dfda297610d3875b950114/versioned/gc/iceberg/pom.xml#L34)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Can you pull this into a separate PR?
The change is fine, just unrelated to the intent of this PR
</blockquote></details>

The PR will fail w/o it. Its annoying but...

Or do you want this as a separate 'pre' PR?

**Review by snazy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1023)* status: 0 of 29 files reviewed, 4 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[servers/store/src/main/java/org/projectnessie/server/store/TableCommitMetaStoreWorker.java, line 47 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkkewX4TPFvkYiNcDt:-MYKGCJR9XJJszhJ5RYY:b-9zko0f) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/servers/store/src/main/java/org/projectnessie/server/store/TableCommitMetaStoreWorker.java#L47)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Sure, can do. Anything specific you are looking for here? I am happy to add a full serde unit test but would rather do that as a separate PR
</blockquote></details>

Fair enough to do it in a separate PR
___
*[versioned/gc/iceberg/pom.xml, line 34 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmHo_MBKRDc3V7FlLT:-MYKFy9aCdev5RWpL6zI:b-hsiojw) ([raw file](https://github.com/projectnessie/nessie/blob/dcb0c486c2a6fcbb48dfda297610d3875b950114/versioned/gc/iceberg/pom.xml#L34)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

The PR will fail w/o it. Its annoying but...

Or do you want this as a separate 'pre' PR?
</blockquote></details>

Yea - just to keep it separate (as not having it might break other stuff) for future reference.

**Review by rymurr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1023)* status: 0 of 29 files reviewed, 4 unresolved discussions (waiting on @laurentgo and @snazy)

___
*[servers/store/src/main/java/org/projectnessie/server/store/TableCommitMetaStoreWorker.java, line 47 at r1](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXkkewX4TPFvkYiNcDt:-MYKIW6A7qv0xBhqaZvZ:b-i8rj2i) ([raw file](https://github.com/projectnessie/nessie/blob/fa98ff00abee09eea8b0817295b07be7c77dc9e1/servers/store/src/main/java/org/projectnessie/server/store/TableCommitMetaStoreWorker.java#L47)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Fair enough to do it in a separate PR
</blockquote></details>

see #1093 
___
*[versioned/gc/iceberg/pom.xml, line 34 at r4](https://reviewable.io/reviews/projectnessie/nessie/1023#-MXmHo_MBKRDc3V7FlLT:-MYKIt7_317VljFl6MdP:bxs4k2x) ([raw file](https://github.com/projectnessie/nessie/blob/dcb0c486c2a6fcbb48dfda297610d3875b950114/versioned/gc/iceberg/pom.xml#L34)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Yea - just to keep it separate (as not having it might break other stuff) for future reference.
</blockquote></details>

see #1092

**Comment by rymurr** [comment]
I think all code review has been addressed and the spec for `id` has been added to the docs. What do you guys think @laurentgo @snazy

**Review by snazy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1023)* status: 0 of 31 files reviewed, 2 unresolved discussions (waiting on @laurentgo)

**Pull request merged**
