### PR TITLE
Garbage collection algorithm leveraging Spark for Nessie

### PR DESCRIPTION
**Pull request by jacques-n**
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/684)

### CODE REVIEW

**Review by rymurr — CHANGES_REQUESTED** [review]
> Reviewed 63 of 63 files at r1.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/684)* status: all files reviewed, 16 unresolved discussions (waiting on @jacques-n)

___
*[versioned/tiered/gc/pom.xml, line 47 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPnzYa7rbkwGGg2Bnt:-MRPnzYb1PTVaYtZDRXy:bu501y1) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/pom.xml#L47)):*
> ```XML
>       <groupId>org.apache.spark</groupId>
>       <artifactId>spark-core_2.12</artifactId>
>       <version>3.0.1</version>
> ```

use `${spark3.version}` here and elsewhere
___
*[versioned/tiered/gc/pom.xml, line 93 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPoLkc4HSc9rF36rYP:-MRPoLkc4HSc9rF36rYQ:bw08t9a) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/pom.xml#L93)):*
> ```XML
>     <dependency>
>       <groupId>org.apache.spark</groupId>
>       <artifactId>spark-sketch_2.12</artifactId>
> ```

this and catalyst are pulled by core. Would prefer to remove, else group all spark deps next to each other
___
*[versioned/tiered/gc/pom.xml, line 103 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPoaUzBDrBGAl2kEeo:-MRPoaUzBDrBGAl2kEep:b56h31k) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/pom.xml#L103)):*
> ```XML
>     </dependency>
>     <dependency>
>       <groupId>software.amazon.awssdk</groupId>
> ```

should this be `test` scope? not sure why this wouldn't be pulled transitively by the version store
___
*[versioned/tiered/gc/pom.xml, line 169 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPsJ9ZBkcbdT6sC4t5:-MRPsJ9_3UYPn5wXt6Jr:b-4l363k) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/pom.xml#L169)):*
> ```XML
> 
>   <build>
>     <pluginManagement>
> ```

move to root pom? Or can it be removed, looks like its no longer being used
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java, line 16 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQKkKs3v_aFOo4XR4u:-MRQKkKs3v_aFOo4XR4v:b3hvmb) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java#L16)):*
> ```Java
>  * limitations under the License.
>  */
> package com.dremio.versioned.gc;
> ```

how come this isnt `com.dremio.nessie.versioned.gc`?
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java, line 53 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPvakx9e8pVvXySXyu:-MRPvakyDnsObr34E11h:b-vallw6) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java#L53)):*
> ```Java
>   private static final Funnel<ByteBuffer> BYTE_FUNNEL = new BinaryFunnel();
>   private static final int SIZE = 10_000_000;
>   private static final Encoder<BinaryBloomFilter> ENCODER = Encoders.kryo(BinaryBloomFilter.class);
> ```

What is the kryo encoder for? It seems from the below code that the bloom filter is typically serialized to bytes 
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java, line 98 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPuiCF95Te0A7sufDj:-MRPuiCF95Te0A7sufDk:bjkvrv5) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java#L98)):*
> ```Java
>         return baos.toByteArray();
>       } catch (IOException e) {
>         throw new RuntimeException("Unexpected.", e);
> ```

any chance we can have a better message here
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java, line 188 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPw4SX9yy55yf1FAZM:-MRPw4SX9yy55yf1FAZN:b64unfy) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java#L188)):*
> ```Java
>     @Override
>     public boolean equals(Object obj) {
>       if (this == obj) {
> ```

this op looks redundant. just `return obj instanceof BinaryFunnel`?
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BytesToGuid.java, line 28 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPwbrD2rsPGWAfg-zq:-MRPwbrD2rsPGWAfg-zr:b-g58bik) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BytesToGuid.java#L28)):*
> ```Java
>  * Spark function to convert binary ids into string guids.
>  */
> class BytesToGuid implements org.apache.spark.sql.api.java.UDF1<byte[], String> {
> ```

do we need the whole package name here?
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdCarrier.java, line 39 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPwu18BhE-z8RS1flK:-MRPwu18BhE-z8RS1flL:bqkw7qm) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdCarrier.java#L39)):*
> ```Java
> import com.dremio.nessie.versioned.store.ValueType;
> 
> public class IdCarrier implements Serializable {
> ```

javadoc?
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdCarrier.java, line 83 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQ6g0w9c47QCCTCXCc:-MRQ6g0w9c47QCCTCXCd:b-k8e4hw) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdCarrier.java#L83)):*
> ```Java
>       @Override
>       public L2 dt(long dt) {
>         return this;
> ```

is this on purpose? Just caught my eye
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdProducer.java, line 40 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQK8fu8cUibffDP-oE:-MRQK8fvCv1y5G97b-GM:b-yaqur1) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdProducer.java#L40)):*
> ```Java
>  * If the current item is valid, generate all the referenced children ids.
>  */
> public class IdProducer {
> ```

can this be package-private and final? I feel like most of the classes could be package-private
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/L1Frame.java, line 98 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQ9Iwf5TaY3RrmZRZP:-MRQ9Iwf5TaY3RrmZRZQ:bu4tpdk) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/L1Frame.java#L98)):*
> ```Java
> 
>   private static List<L1Parent> toParents(Stream<Id> unfilteredParents) {
>     List<Id> pre = unfilteredParents.collect(Collectors.toList());
> ```

any reason to collect to a list then 're-stream'?
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/RefToL2Producer.java, line 65 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQFFe34AD6YadQrcEz:-MRQFFe34AD6YadQrcF-:b-n5x15x) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/RefToL2Producer.java#L65)):*
> ```Java
> 
>       // the potential items joined with the available l1s.
>       final Dataset<Row> joined = spark.sql(
> ```

I am curious about the performance for large histories. Its not clear to me that spark will know how to parallelize this onto multiple executors. We may end up with 1 executor holding the entire dataset. I think at the very least a `repartition` should be called at some point. As I have mentioned before I think the end state for this should be a `DataSource`, which would allow more control over partitions/parallelism.

Having said that my Spark is rusty and we should investigate to be certain.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/ValueRetriever.java, line 64 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQG1dY39yXz8FGdBQR:-MRQG1dY39yXz8FGdBQS:b-3wfegy) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/ValueRetriever.java#L64)):*
> ```Java
>   public Dataset<OUT> get(SparkSession spark, Optional<Predicate<OUT>> filter) {
>     List<OUT> out = this.stream().filter(filter.orElse(t -> true)).collect(Collectors.toList());
>     return spark.createDataset(out, Encoders.bean(clazz));
> ```

doing the filter in spark instead of on the stream is a possibility. I think it has its advantages for larger datasets and parallelism
___
*[versioned/tiered/gc/src/test/java/com/dremio/versioned/gc/ITTestIdentifyUnreferencedAssets.java, line 105 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQH-qa0VasZ57cpGBn:-MRQH-qa0VasZ57cpGBo:b-g9oqa4) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/test/java/com/dremio/versioned/gc/ITTestIdentifyUnreferencedAssets.java#L105)):*
> ```Java
>         .builder()
>         .appName("test-nessie-gc-collection")
>         .master("local")
> ```

maybe want local[2] to force parallelism

**Comment by rymurr** [comment]
Just added a bunch of nits and cosmetic stuff. Overall I like the algo but am slightly concerned about how it would perform on Spark with a real sized database. Probably can be tackled in a further iteration of the algo though.

**Review by jacques-n — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/684)* status: all files reviewed, 16 unresolved discussions (waiting on @rymurr)

___
*[versioned/tiered/gc/pom.xml, line 47 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPnzYa7rbkwGGg2Bnt:-MRRVH7_4Gugw_9ONxAg:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/pom.xml#L47)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

use `${spark3.version}` here and elsewhere
</blockquote></details>

Done.
___
*[versioned/tiered/gc/pom.xml, line 93 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPoLkc4HSc9rF36rYP:-MRRVTRG4hv2ZbrIMpUG:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/pom.xml#L93)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

this and catalyst are pulled by core. Would prefer to remove, else group all spark deps next to each other
</blockquote></details>

Done.
___
*[versioned/tiered/gc/pom.xml, line 103 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPoaUzBDrBGAl2kEeo:-MRRVcwC6kNdHV_Ysn7Q:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/pom.xml#L103)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

should this be `test` scope? not sure why this wouldn't be pulled transitively by the version store
</blockquote></details>

Done.
___
*[versioned/tiered/gc/pom.xml, line 169 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPsJ9ZBkcbdT6sC4t5:-MRRVdKh5lKxu2RKO2a9:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/pom.xml#L169)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

move to root pom? Or can it be removed, looks like its no longer being used
</blockquote></details>

Done.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java, line 16 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQKkKs3v_aFOo4XR4u:-MRRVmGk-_DFPuWwDs-J:b-qssebl) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java#L16)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

how come this isnt `com.dremio.nessie.versioned.gc`?
</blockquote></details>

fixed.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java, line 53 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPvakx9e8pVvXySXyu:-MRRVxTfD_7rtoADQyZC:b54nda1) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java#L53)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

What is the kryo encoder for? It seems from the below code that the bloom filter is typically serialized to bytes 
</blockquote></details>

two different serializations due to api constraints. See javadoc. The kryo one is used in the internals of spark for the aggregation udf intermediate state.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java, line 98 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPuiCF95Te0A7sufDj:-MRRWL624EHLedD-hJuC:bx73w3b) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java#L98)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

any chance we can have a better message here
</blockquote></details>

improved. It should be impossible to hit.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java, line 188 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPw4SX9yy55yf1FAZM:-MRRWXWoDuGp-QE6Ri7l:bxl3lky) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java#L188)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

this op looks redundant. just `return obj instanceof BinaryFunnel`?
</blockquote></details>

fixed. It was auto-generated before being manipulated.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BytesToGuid.java, line 28 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPwbrD2rsPGWAfg-zq:-MRRWcmZ89O1rty82yAM:b-nwju65) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BytesToGuid.java#L28)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

do we need the whole package name here?
</blockquote></details>

yes, otherwise there is some kind of checkstyle issue with import ordering that i couldn't figure out how to resolve... 
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdCarrier.java, line 39 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPwu18BhE-z8RS1flK:-MRRX6Lr7wTWR308_txc:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdCarrier.java#L39)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

javadoc?
</blockquote></details>

Done.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdCarrier.java, line 83 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQ6g0w9c47QCCTCXCc:-MRRXCen7TDzid2g0GRL:b9aime0) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdCarrier.java#L83)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

is this on purpose? Just caught my eye
</blockquote></details>

Yes, we don't currently use that value. Added comment.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdProducer.java, line 40 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQK8fu8cUibffDP-oE:-MRRXMeqAhd3UI9TSVrY:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/IdProducer.java#L40)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

can this be package-private and final? I feel like most of the classes could be package-private
</blockquote></details>

Done.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/L1Frame.java, line 98 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQ9Iwf5TaY3RrmZRZP:-MRRXY6dClTLqEIXyz3U:b-9snu0o) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/L1Frame.java#L98)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

any reason to collect to a list then 're-stream'?
</blockquote></details>

debugging remnant. Fixed.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/RefToL2Producer.java, line 65 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQFFe34AD6YadQrcEz:-MRRXatRC0FQOJag9H2L:b-wfuhdq) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/RefToL2Producer.java#L65)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

I am curious about the performance for large histories. Its not clear to me that spark will know how to parallelize this onto multiple executors. We may end up with 1 executor holding the entire dataset. I think at the very least a `repartition` should be called at some point. As I have mentioned before I think the end state for this should be a `DataSource`, which would allow more control over partitions/parallelism.

Having said that my Spark is rusty and we should investigate to be certain.
</blockquote></details>

I see this as a problem of the frame.asDataset operations. The sql itself should be intelligently scheduled by Spark (I'd hope).
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/ValueRetriever.java, line 64 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQG1dY39yXz8FGdBQR:-MRRXrwm35UDgzFnswvV:b6fpedv) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/ValueRetriever.java#L64)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

doing the filter in spark instead of on the stream is a possibility. I think it has its advantages for larger datasets and parallelism
</blockquote></details>

It depends. Since the filter is opaque, it requires reconstructing the dataset objects (as opposed to direct row access). If we could use an expression instead of an opaque predicate, you're probably right. Until we parallelize the ValueRetriever access, this seems more efficient (you can potentially skip reconstituting the frame objects depending on what you do afterwards.
___
*[versioned/tiered/gc/src/test/java/com/dremio/versioned/gc/ITTestIdentifyUnreferencedAssets.java, line 105 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQH-qa0VasZ57cpGBn:-MRR_CJ7BcdAhM_R1aa5:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/test/java/com/dremio/versioned/gc/ITTestIdentifyUnreferencedAssets.java#L105)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

maybe want local[2] to force parallelism
</blockquote></details>

Done.

**Review by rymurr — APPROVED** [review]
> Reviewed 1 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/684)* status: 35 of 64 files reviewed, 12 unresolved discussions (waiting on @rymurr)

___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java, line 53 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPvakx9e8pVvXySXyu:-MRUaZc_Dz6CAWrly4Wg:b-w6lzd7) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BinaryBloomFilter.java#L53)):*
<details><summary><i>Previously, jacques-n (Jacques Nadeau) wrote…</i></summary><blockquote>

two different serializations due to api constraints. See javadoc. The kryo one is used in the internals of spark for the aggregation udf intermediate state.
</blockquote></details>

got it, was confused by the javadoc as the guava readFrom is used in the Externalizable too. 

I see the Kryo codec is used in the Spark encoder and thought it could be replaced by the externalizable based serialization already there. Don't see immediately how to though.
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BytesToGuid.java, line 28 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRPwbrD2rsPGWAfg-zq:-MRUe6Y157ni_1GGiHGU:bxxgm4y) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/BytesToGuid.java#L28)):*
<details><summary><i>Previously, jacques-n (Jacques Nadeau) wrote…</i></summary><blockquote>

yes, otherwise there is some kind of checkstyle issue with import ordering that i couldn't figure out how to resolve... 
</blockquote></details>

bizarre
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/RefToL2Producer.java, line 65 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQFFe34AD6YadQrcEz:-MRUeHvFCD3TU_-li69g:b-avgj5w) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/RefToL2Producer.java#L65)):*
> I see this as a problem of the frame.asDataset operations.
agreed

>  The sql itself should be intelligently scheduled by Spark (I'd hope).
thats very optimistic of you ;-)

Either way, something for a future revision
___
*[versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/ValueRetriever.java, line 64 at r1](https://reviewable.io/reviews/projectnessie/nessie/684#-MRQG1dY39yXz8FGdBQR:-MRUgzjRAXSvCLS_h6Tl:b8hzizu) ([raw file](https://github.com/projectnessie/nessie/blob/faab9537430dfde0f5cc3debf8459d495550b449/versioned/tiered/gc/src/main/java/com/dremio/versioned/gc/ValueRetriever.java#L64)):*
<details><summary><i>Previously, jacques-n (Jacques Nadeau) wrote…</i></summary><blockquote>

It depends. Since the filter is opaque, it requires reconstructing the dataset objects (as opposed to direct row access). If we could use an expression instead of an opaque predicate, you're probably right. Until we parallelize the ValueRetriever access, this seems more efficient (you can potentially skip reconstituting the frame objects depending on what you do afterwards.
</blockquote></details>

agreed, something to tackle in the long term

**Comment by rymurr** [comment]
I am happy with this algorithm. I think we should follow up on performance related stuff in a separate PR. See #706

Something not addressed in this change that we should have a discussion is:
1) how to actually invoke this algorithm?
1) What to do with the results?

I have opened #707 to track these questions

**Review by rymurr — APPROVED** [review]
Rock on! Can't wait to use this in anger

**Pull request merged**
