### PR TITLE
Use Quarkus BOM version of MongoDB

### PR DESCRIPTION
**Pull request by kylepbit**
Remove MongoDB from dependencyMangagement in favour of versions in the Quarkus BOM to avoid version mismatches.

Keep flapdoodle as we rely on a later version then is in the Quarkus BOM.

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/850)

### CODE REVIEW

**Comment by jacques-n** [comment]
Is there a compatibility reason why reactive streams isn't pointing at the right Mongo. It seems a little weird to upgrade underneath our client library.

Also, isn't Mongo in the Quarkus BOM? Are we comfortable changing from what is there?

**Comment by laurentgo** [comment]
Checking https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-reactivestreams/4.2.1/mongodb-driver-reactivestreams-4.2.1.pom, the dependency seems correct to me, and I would suspect that Quarkus BOM might be the culprit: https://search.maven.org/artifact/io.quarkus/quarkus-bom/1.12.0.Final/pom

**Comment by rymurr** [comment]
the mongo deps in our pom are also available in quarkus bom. I suspect its better to just keep compatibility w/ quarkus and remove mongo references from our `dependenciesManagement` section. We tried to be different from quarkus w/ both opentracing and metrics and it didn't work great.

**Comment by kylepbit** [comment]
Updated to use the Quarkus version, thanks for the pointer on that.

**Review by rymurr — APPROVED** [review]
LGTM! Thanks @kylepbit

**Pull request merged**
