### PR TITLE
Fix Quarkus ConfigProperties deprecation

### PR DESCRIPTION
**Pull request by rymurr**
@laurentgo s work + checkstyle fixes

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1563)

### CODE REVIEW

**Review by nastra — APPROVED** [review]

**Comment by rymurr** [comment]
This is behaving incorrectly. Have raised quarkusio/quarkus#18524

**Comment by rymurr** [comment]
This is now blocked on https://github.com/quarkusio/quarkus/pull/18497

**Comment by rymurr** [comment]
@nastra does #1814 replace this?

**Comment by nastra** [comment]
@rymurr yep it does

**Pull request closed without merging**
