### PR TITLE
Avoid parallel streams If parallelism is one.

### PR DESCRIPTION
**Pull request by nk1506**
If parallelism is explicitly one, It should use sequential streams.

### CODE REVIEW

**Review by snazy — COMMENTED** [review]
Both changed code blocks are rather long running tasks, usually tasks that have rather long (I/O-)wait times, so parallelism==1 would significantly slow those down. The overhead of parallelism==1 is negligible considering the time spent in these tasks.

Given that #7150 had to be reverted due to ending in using the default `ForkJoinPool`, because of "unguarded" `Stream.parallel()`, I'm not sure that a future change (introducing another `Stream.parallel()`) might not run into the same situation.

Thinking a bit more about this, can you maybe elaborate on the overall goals?

**Comment by harshm-dev** [comment]
Trying to use it in Dremio. Overhead is not really the reason.
RequestContext (in the thread local) is lost once the control moves to ForkJoinPool, which is used during gRPC communication.

In general, the preference is to perform within the executor's thread as there building blocks there with the assumption; aforementioned could only be one of the reasons.

@nk1506 Is it possible to extend the checks wrt `Stream.parallel()` ?

**Comment by nk1506** [comment]
Thanks @snazy  for reviewing. I am totally on the same page with [comment](https://github.com/projectnessie/nessie/pull/7155#pullrequestreview-1504942451. ) where adding another `Stream.parallel()` can end up with same problem. 

Although this changes was required for one of the engine where it is using threadLocal to set some context. Aftre Using `ForkJoinPool` , Engine was loosing the context for nessie rest calls. 

I am abandoning this change as we found a workaround.

**Comment by snazy** [comment]
Note that there's a potential to enhance the GC code to use a custom ForkJoinThreadFactory, requires a PR though.

**Pull request closed without merging**
